NMS_MOD_DEFINITION_CONTAINER = {
["MOD_FILENAME"]	= "GSound 231a Cuboid.pak",
["MOD_DESCRIPTION"]	= "Silence Cuboid decoration",
["MOD_AUTHOR"]		= "Gumsk",
["NMS_VERSION"]		= "2.3.1",
["MODIFICATIONS"]	= {{
	["MBIN_CHANGE_TABLE"] = {{
	["MBIN_FILE_SOURCE"] = "MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\PARTS\BUILDABLEPARTS\FOLIAGE\WEIRDCUBE\ENTITIES\CUBOIDSMALL.ENTITY.MBIN",
	["EXML_CHANGE_TABLE"] = {{
		["VALUE_CHANGE_TABLE"] = {
			{"Ambient", ""}
}}}},}}}}