>>> MapFileTree: GCDEBUGOPTIONS.GLOBAL.EXML (NMSARC.59B126E2.pak) "2022/03/16-18:47:55"
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 TYPE:FILELINE:LEVEL     KEYWORDS
{[   :       3: 0]GcDebugOptions --Do not use, NOT a KEYWORD
:[.su:       4: 1]  {"ForceScanEventsToGoPrime","False",},
:[.su:       5: 1]  {"SkipAbandonedFreighterUnlocking","False",},
:[.su:       6: 1]  {"AllowSavingOnAbandonedFreighters","False",},
:[.su:       7: 1]  {"DisableAbandonedFreighterRoomsOptimisation","False",},
:[.su:       8: 1]  {"OverrideAbandonedFreighterSeed","0",},
:[.su:       9: 1]  {"ThirdPersonIsDefaultCamera","True",},
:[.su:      10: 1]  {"SkipIntro","False",},
:[.su:      11: 1]  {"SkipLogos","False",},
:[.su:      12: 1]  {"BootDirectlyIntoSaveSlot","-1",},
:[.su:      13: 1]  {"BootDirectlyIntoLastSave","False",},
{[PSU:      14: 1]  "NewSaveGameMode", / {"NewSaveGameMode","GcGameMode.xml",},
:[.SU:      15: 2]  | {"PresetGameMode","Unspecified",},
:[   :      16: 1]  <<< }
:[.su:      17: 1]  {"SkipPlanetDiscoverOnBoot","False",},
:[.su:      18: 1]  {"VideoCaptureMode","False",},
:[.su:      19: 1]  {"GodMode","False",},
:[.su:      20: 1]  {"TakeNoDamage","False",},
:[.su:      21: 1]  {"SuperKillGuns","False",},
:[.su:      22: 1]  {"AlwaysHaveFocus","False",},
:[.su:      23: 1]  {"DisableVibration","False",},
:[.su:      24: 1]  {"DebugGalaxyMapInQuickMenu","False",},
:[.su:      25: 1]  {"MapWarpCheckIgnoreFuel","False",},
:[.su:      26: 1]  {"MapWarpCheckIgnoreDrive","False",},
:[.su:      27: 1]  {"EverythingIsFree","False",},
:[.su:      28: 1]  {"EverythingIsKnown","False",},
:[.su:      29: 1]  {"EverythingIsStar","False",},
:[.su:      30: 1]  {"InfiniteStamina","False",},
:[.su:      31: 1]  {"DisableHazards","False",},
:[.su:      32: 1]  {"IgnoreMissionRank","False",},
:[.su:      33: 1]  {"CanLeaveDialogs","False",},
:[.su:      34: 1]  {"DisableOldMissions","True",},
:[.su:      35: 1]  {"UseScreenEffects","True",},
:[.su:      36: 1]  {"UseGunImpactEffect","True",},
:[.su:      37: 1]  {"RenderCreatureDetails","False",},
:[.su:      38: 1]  {"SkipTutorial","False",},
:[.su:      39: 1]  {"IgnoreFreighterSpawnWarpRequirement","False",},
:[.su:      40: 1]  {"MaximumFreighterSpawns","False",},
:[.su:      41: 1]  {"DisableSaveSlotSorting","False",},
:[.su:      42: 1]  {"DisableSaving","False",},
:[.su:      43: 1]  {"DisableStorms","False",},
:[.su:      44: 1]  {"AlternateControls","False",},
:[.su:      45: 1]  {"AlwaysShowURI","True",},
:[.su:      46: 1]  {"MPMissionsAlwaysEPIC","False",},
:[.su:      47: 1]  {"ShowFireteamMembersUA","False",},
:[.su:      48: 1]  {"RevealAllTitles","False",},
:[.su:      49: 1]  {"UnlockAllTitles","False",},
:[.su:      50: 1]  {"LockAllTitles","False",},
:[.su:      51: 1]  {"AlwaysAllowShipOperations","False",},
:[.su:      52: 1]  {"AlwaysAllowVehicleOperations","False",},
:[.su:      53: 1]  {"AlwaysAllowFreighterInventoryAccess","False",},
:[.su:      55: 1]  {"UnlockAllSeasonRewards","False",},
:[.su:      56: 1]  {"UnlockAllTwitchRewards","False",},
:[.su:      58: 1]  {"AllowPause","True",},
:[.su:      59: 1]  {"AllSettlementsAreCompleted","False",},
:[.su:      60: 1]  {"DisableSettlements","False",},
:[.su:      61: 1]  {"PlaceOnGroundWhenLeavingDebugCamera","True",},
:[.su:      62: 1]  {"EnableOctohedralImposters","False",},
:[.su:      63: 1]  {"UseDebugScreenSettings","False",},
:[.su:      64: 1]  {"ScreenWidth","1920",},
:[.su:      65: 1]  {"ScreenHeight","1080",},
:[.su:      66: 1]  {"DisableVSync","False",},
:[.SU:      67: 1]  {"GameWindowMode","Bordered",},
:[.su:      68: 1]  {"Monitor","0",},
:[.su:      69: 1]  {"TiledWindowsSplitCount","2",},
:[.su:      70: 1]  {"TiledWindowsIndex","-1",},
:[.su:      73: 1]  {"ForceInitialShip","True",},
:[.su:      74: 1]  {"ForceInitialWeapon","True",},
:[.SU:      75: 1]  {"GameStateMode","UserStorage",},
:[.SU:      76: 1]  {"BootMode","SolarSystem",},
:[.SU:      77: 1]  {"PlayerSpawnLocationOverride","GameStartPlanet",},
:[.SU:      78: 1]  {"SceneSettings","SCENES/DEMOS/MARCH19VR/MAINSETTINGS.MXML",},
:[.SU:      79: 1]  {"WorkingDirectory","SCENES/DEMOS/MARCH19VR",},
:[.SU:      80: 1]  {"DebugScene","METADATA/SIMULATION/DEBUGSCENE.MBIN",},
:[.SU:      81: 1]  {"SolarSystemBoot","Generate",},
:[.SU:      82: 1]  {"ShaderPreload","Off",},
:[.su:      83: 1]  {"ShaderPreloadListExport","False",},
:[.su:      84: 1]  {"ShaderPreloadListImport","False",},
:[.su:      85: 1]  {"ShaderCaching","False",},
:[.SU:      86: 1]  {"BootLoadDelay","LoadAll",},
:[.su:      87: 1]  {"MemCsv","False",},
:[.su:      88: 1]  {"ForceTimeOfDay","-1",},
:[.su:      89: 1]  {"ForceInitialTimeOfDay","-1",},
:[.su:      90: 1]  {"ForceSunDirectionFromPhotoMode","False",},
:[.su:      91: 1]  {"ForceSunAngle","0",},
:[.su:      92: 1]  {"ResetForcedSaveSlotOnLoad","False",},
:[.su:      93: 1]  {"MissionMessageLoggingEnabled","False",},
:[.su:      94: 1]  {"UseParticles","True",},
:[.su:      95: 1]  {"UseHeavyAir","True",},
:[.su:      96: 1]  {"UseVolumetrics","True",},
:[.su:      97: 1]  {"UseClouds","True",},
:[.su:      98: 1]  {"EnableCloudAnimation","True",},
:[.su:      99: 1]  {"UseTerrain","True",},
:[.su:     100: 1]  {"UseInstances","True",},
:[.su:     101: 1]  {"UseObjects","True",},
:[.su:     102: 1]  {"UseBuildings","True",},
:[.su:     103: 1]  {"UseCreatures","True",},
:[.su:     104: 1]  {"UseElevation","True",},
:[.su:     105: 1]  {"UseLegacyFreighters","False",},
:[.su:     106: 1]  {"UseLegacyBuildingTable","False",},
:[.su:     107: 1]  {"EnableDayNightCycle","True",},
:[.su:     108: 1]  {"SpawnPirates","True",},
:[.su:     109: 1]  {"SpawnRobots","True",},
:[.su:     110: 1]  {"SpawnShips","True",},
:[.su:     111: 1]  {"SpawnPulseEncounters","True",},
:[.su:     112: 1]  {"InstanceCollision","True",},
:[.su:     113: 1]  {"LoadMissions","True",},
:[.su:     114: 1]  {"MPMissions","True",},
:[.su:     115: 1]  {"SpecialsShop","False",},
:[.su:     116: 1]  {"MultiplePlayerFreightersInASystem","False",},
:[.su:     117: 1]  {"ForceNexusInQuickMenu","False",},
:[.su:     118: 1]  {"MissionSurveyEnabled","True",},
:[.su:     119: 1]  {"AllSeasonMilestonesShowComplete","False",},
:[.su:     120: 1]  {"EnableGalaxyRecolouring","False",},
:[.su:     121: 1]  {"IgnoreSteamDev","False",},
:[.su:     122: 1]  {"EnableBaseBuildingExpandables","False",},
:[.su:     123: 1]  {"MouseLookEnabled","True",},
:[.su:     124: 1]  {"StartPaused","False",},
:[.su:     125: 1]  {"DisableDebugControls","False",},
:[.su:     126: 1]  {"FixedFramerate","False",},
:[.su:     127: 1]  {"ScreenshotMode","False",},
:[.su:     128: 1]  {"RenderHud","True",},
:[.su:     129: 1]  {"DisableDiscoveryNaming","False",},
:[.su:     130: 1]  {"DebugDrawPlayerInteract","False",},
:[.su:     131: 1]  {"ForceInteractionToSettings","False",},
:[.su:     132: 1]  {"ForceInteractionIndex","0",},
:[.su:     133: 1]  {"InteractionsAllwaysGivesTech","False",},
:[.su:     134: 1]  {"InfiniteInteractions","False",},
:[.su:     135: 1]  {"StopSwitchingToSecondaryInteractions","False",},
{[PSU:     136: 1]  "DebugLanguage", / {"DebugLanguage","TkLanguages.xml",},
:[.SU:     137: 2]  | {"Language","Default",},
:[   :     138: 1]  <<< }
:[.SU:     139: 1]  {"AllowedLanguagesFile","DEFAULT",},
:[.su:     140: 1]  {"DoAlienLanguage","True",},
{[PSU:     141: 1]  "ForceInteractionRaceTo", / {"ForceInteractionRaceTo","GcAlienRace.xml",},
:[.S.:     142: 2]  | {"AlienRace","Traders",},
:[   :     143: 1]  <<< }
:[.SU:     144: 1]  {"RealityMode","LoadPreset",},
:[.su:     145: 1]  {"DebugPersistentInteractions","False",},
:[.su:     146: 1]  {"UseHighlightedOptionStyle","True",},
:[.su:     147: 1]  {"DisableMissionShop","False",},
:[.SU:     148: 1]  {"RealityPresetFile","METADATA/REALITY/DEFAULTREALITY.MBIN",},
:[.su:     149: 1]  {"RealityGenerationIteration","0",},
{[P..:     150: 1]  "LocTableList",
{[P..:     151: 2]  | "NMSString0x20.xml",
:[.SU:     152: 3]  | | {"Value","NMS_Loc1",},
:[   :     153: 2]  | <<< }
{[P..:     154: 2]  | "NMSString0x20.xml",
:[.SU:     155: 3]  | | {"Value","NMS_Update3",},
:[   :     156: 2]  | <<< }
{[P..:     157: 2]  | "NMSString0x20.xml",
:[.SU:     158: 3]  | | {"Value","NMS_Loc4",},
:[   :     159: 2]  | <<< }
{[P..:     160: 2]  | "NMSString0x20.xml",
:[.SU:     161: 3]  | | {"Value","NMS_Loc5",},
:[   :     162: 2]  | <<< }
{[P..:     163: 2]  | "NMSString0x20.xml",
:[.SU:     164: 3]  | | {"Value","NMS_Loc6",},
:[   :     165: 2]  | <<< }
{[P..:     166: 2]  | "NMSString0x20.xml",
:[.SU:     167: 3]  | | {"Value","NMS_Loc7",},
:[   :     168: 2]  | <<< }
:[   :     169: 1]  <<< }
:[.SU:     170: 1]  {"DefaultSaveData","METADATA/GAMESTATE/DEFAULTSAVEDATA.MBIN",},
:[.su:     171: 1]  {"FormatDownloadStorageAreaOnBoot","False",},
:[.su:     172: 1]  {"ForceBasicLoadScreen","False",},
:[.su:     173: 1]  {"BootLogoFadeRate","2.5",},
:[.su:     174: 1]  {"BootMusic","True",},
:[.su:     175: 1]  {"WeaponScale3P","0.55",},
:[.su:     176: 1]  {"LogMissingLocalisedText","False",},
:[.su:     177: 1]  {"FleetDirectorAutoMode","True",},
:[.su:     178: 1]  {"_3dTextDistance","200",},
:[.su:     179: 1]  {"_3dTextMinScale","2",},
:[.SU:     180: 1]  {"RecordSetting","None",},
:[.su:     181: 1]  {"DebugBuildingSpawns","False",},
:[.su:     182: 1]  {"StressTestLongNameDisplay","False",},
:[.su:     183: 1]  {"ShowLongestStrings","False",},
:[.su:     185: 1]  {"NeverUseBanks","False",},
:[.su:     186: 1]  {"DisableProfanityFilter","False",},
:[.su:     187: 1]  {"DisableFileWatcher","False",},
:[.su:     188: 1]  {"DisableShaderReload","True",},
:[.su:     189: 1]  {"RecurrenceTimeOffset","0",},
:[.su:     192: 1]  {"EnableLivePP","False",},
:[.su:     193: 1]  {"DebugThreatLevels","False",},
:[.su:     194: 1]  {"ShowDebugMessages","True",},
:[.su:     195: 1]  {"ShowFramerate","False",},
:[.su:     196: 1]  {"PrintAvgFrameTimes","False",},
:[.su:     197: 1]  {"ShowPositionDebug","False",},
:[.su:     198: 1]  {"ShowGPUMemory","True",},
:[.su:     199: 1]  {"ShowMempoolOverlay","False",},
:[.su:     200: 1]  {"ShowMouseSmoothing","False",},
:[.su:     202: 1]  {"ShowGraphs","False",},
:[.su:     203: 1]  {"ShowSpecificGraph","-1",},
:[.su:     204: 1]  {"GraphCommandBuffer","False",},
:[.su:     205: 1]  {"GraphGeneration","True",},
:[.su:     206: 1]  {"GraphFPS","True",},
:[.su:     207: 1]  {"GraphTexStreaming","False",},
:[.su:     208: 1]  {"SmokeTestDumpStatsMode","False",},
:[.SU:     209: 1]  {"SmokeTestCycleMode","None",},
:[.SU:     210: 1]  {"SmokeTestScenario","None",},
:[.su:     211: 1]  {"SmokeTestLegacyOutput","False",},
:[.su:     212: 1]  {"SmokeTestConfigPlanetPositionCount","10",},
:[.su:     213: 1]  {"SmokeTestConfigScenarioPreambleLength","10",},
:[.su:     214: 1]  {"SmokeTestConfigScenarioLength","5",},
:[.su:     215: 1]  {"SmokeTestFastExit","True",},
:[.su:     216: 1]  {"SmokeTestCameraFly","False",},
:[.su:     217: 1]  {"SmokeTestOutputOnly","False",},
:[.su:     218: 1]  {"SmokeTestPureFlight","False",},
:[.su:     219: 1]  {"SmokeTestConfigCaptureCycles","3",},
:[.su:     220: 1]  {"SmokeTestConfigCaptureDurationInSeconds","20",},
:[.su:     221: 1]  {"SmokeTestConfigCaptureFolderNameNumberOffset","5",},
:[.su:     222: 1]  {"SmokeTestConfigRandomizePlanetSeed","False",},
:[.su:     223: 1]  {"SmokeTestSmokeBotEnabled","False",},
:[.su:     224: 1]  {"SmokeTestSmokeBotAutoStart","False",},
:[.su:     225: 1]  {"SmokeTestSmokeBotTargetWarps","0",},
:[.su:     226: 1]  {"SmokeTestPostBandwidthStats","False",},
:[.SU:     227: 1]  {"SmokeTestForcePlanetDetail","Ultra",},
:[.su:     229: 1]  {"CreatureChatter","False",},
:[.su:     230: 1]  {"CreatureErrors","False",},
:[.su:     231: 1]  {"CreatureDrawVocals","False",},
:[.su:     232: 1]  {"DrawCreaturesInRoutines","False",},
:[.su:     233: 1]  {"CompressTextures","True",},
:[.su:     234: 1]  {"DebugIBL","False",},
:[.su:     235: 1]  {"DebugTerrainTextures","False",},
:[.su:     236: 1]  {"DisableShadowSwitching","False",},
:[.SU:     237: 1]  {"PipelineFile","PIPELINES/PIPELINEDEFERRED.BIN",},
:[.SU:     238: 1]  {"PipelineFilePS4","PIPELINES/PIPELINEDEFERREDPS4.BIN",},
:[.SU:     239: 1]  {"PipelineFileXboxOne","PIPELINES/PIPELINEDEFERRED.BIN",},
:[.SU:     240: 1]  {"PipelineFileVR","PIPELINES/PIPELINEDEFERREDVR.BIN",},
:[.SU:     241: 1]  {"PipelineFileVRPS4","PIPELINES/PIPELINEDEFERREDVRPS4.BIN",},
:[.SU:     242: 1]  {"PipelineFileFrontend","PIPELINES/PIPELINENGUISCREENVIEW.BIN",},
:[.SU:     243: 1]  {"PipelineFileEditor","PIPELINES/PIPELINENGUISCREENVIEW.BIN",},
:[.su:     244: 1]  {"RenderLowFramerate","True",},
:[.su:     245: 1]  {"EnableComputePost","True",},
:[.su:     246: 1]  {"EnableEvenOddRender","False",},
:[.su:     247: 1]  {"MinGPUMode","False",},
:[.su:     248: 1]  {"Proto2DevKit","False",},
:[.su:     249: 1]  {"AlwaysIncludeLocalPlayerInChatMessage","False",},
:[.su:     250: 1]  {"SimulateNoNetworkConnection","False",},
:[.SU:     251: 1]  {"ProxyType","InetProxy",},
:[.SU:     252: 1]  {"ProxyURI","localhost:8888",},
:[.SU:     253: 1]  {"ServerEnv","Default",},
:[.SU:     254: 1]  {"AuthBaseUrl","-nms-auth.nomanssky.com",},
:[.su:     255: 1]  {"CertificateSecurityBypass","False",},
:[.su:     257: 1]  {"DiscoveryAutoSyncIntervalSeconds","0",},
:[.su:     258: 1]  {"DisableSpaceStationSpawnOnJoin","False",},
:[.su:     259: 1]  {"AutoJoinUserEnabled","False",},
:[.su:     261: 1]  {"AlwaysSaveGameAsClient","False",},
:[.su:     262: 1]  {"DisableMonumentDownloads","False",},
:[.su:     263: 1]  {"UsePadOnUnfocusedWindow","False",},
:[.su:     264: 1]  {"OverrideMatchmakingVersion","0",},
:[.su:     266: 1]  {"IgnoreTransactionTimeouts","False",},
:[.su:     267: 1]  {"AutoJoinRandomGames","False",},
:[.su:     269: 1]  {"RecordNetworkStatsOnBoot","False",},
:[.su:     270: 1]  {"FakeHandsInMultiplayer","False",},
:[.su:     271: 1]  {"ForceSmallLobby","False",},
:[.su:     272: 1]  {"OverrideServerSeasonNumber","0",},
:[.su:     273: 1]  {"OverrideServerSeasonEndTime","0",},
:[.su:     274: 1]  {"EnableSynergy","True",},
:[.su:     276: 1]  {"SynergyPort","24800",},
:[.su:     277: 1]  {"ShowEditorPlacementPreview","True",},
:[.su:     278: 1]  {"MaxNumDebugMessages","100",},
:[.su:     279: 1]  {"PreloadToolbox","False",},
:[.su:     280: 1]  {"DebugTextureSize","1080",},
:[.su:     281: 1]  {"UseProcTextureDebugger","False",},
:[.su:     282: 1]  {"ProceduralModelsShown","30",},
:[.su:     283: 1]  {"ProceduralModelBatchSize","30",},
:[.su:     284: 1]  {"ProceduralModelFilterMatchretryCount","5000",},
:[.su:     285: 1]  {"ProceduralModelsDeterministicSequence","True",},
:[.su:     286: 1]  {"ProceduralModelsThumbnailSize","128",},
:[.SU:     287: 1]  {"DebugFont","FONTS/DEBUGMONKEY.FNT",},
:[.SU:     288: 1]  {"DebugFontTexture","TEXTURES/FONTS/DEBUGMONKEY.DDS",},
:[.SU:     289: 1]  {"CursorTexture","TEXTURES/UI/IMGUI//CURSOR.DDS",},
:[.SU:     290: 1]  {"PauseTexture","TEXTURES/UI/IMGUI//PAUSE.DDS",},
:[.SU:     291: 1]  {"PlayTexture","TEXTURES/UI/IMGUI//PLAY.DDS",},
:[.SU:     292: 1]  {"StepTexture","TEXTURES/UI/IMGUI//STEP.DDS",},
:[.SU:     293: 1]  {"RenderToTexture","TEXTURES/DEBUG/RENDERTO.DDS",},
:[.su:     294: 1]  {"HmdEnable","True",},
:[.su:     295: 1]  {"HmdPreviewScale","2",},
:[.su:     296: 1]  {"HmdTracking","False",},
:[.su:     297: 1]  {"HmdStereoRender","False",},
:[.su:     298: 1]  {"HmdDistortionPassthru","False",},
:[.su:     299: 1]  {"HmdMonitor","-1",},
:[.su:     300: 1]  {"HmdEyeBufferWidth","0",},
:[.su:     301: 1]  {"HmdEyeBufferHeight","0",},
:[.su:     302: 1]  {"HmdEyeScalePos","1.4",},
:[.su:     303: 1]  {"HmdHeadScalePos","1.4",},
:[.su:     304: 1]  {"HmdFrameShiftEnabled","False",},
:[.su:     305: 1]  {"HmdUseSolidGuiPointer","False",},
:[.su:     306: 1]  {"BodyTurning","False",},
:[.su:     307: 1]  {"HmdImmersionFactor","9000.1",},
:[.su:     308: 1]  {"ShowHmdHandControllers","False",},
:[.su:     309: 1]  {"ShowTeleportEffectLocally","True",},
:[.su:     310: 1]  {"DisableLeftHand","False",},
:[.su:     311: 1]  {"DisableHeadConstraints","False",},
:[.su:     312: 1]  {"EnablePhotomodeVR","False",},
:[.su:     313: 1]  {"AllowNGuiVR","False",},
:[.su:     314: 1]  {"ForceExtremeWeather","False",},
:[.su:     315: 1]  {"ForceExtremeSentinels","False",},
:[.su:     316: 1]  {"ForceStarType","False",},
:[.su:     317: 1]  {"ForceLoadAllWeather","False",},
{[PSU:     318: 1]  "ForceStarTypeTo", / {"ForceStarTypeTo","GcGalaxyStarTypes.xml",},
:[.SU:     319: 2]  | {"GalaxyStarType","Red",},
:[   :     320: 1]  <<< }
:[.su:     321: 1]  {"ForceBiome","False",},
{[PSU:     322: 1]  "ForceBiomeTo", / {"ForceBiomeTo","GcBiomeType.xml",},
:[.SU:     323: 2]  | {"Biome","Barren",},
:[   :     324: 1]  <<< }
:[.su:     325: 1]  {"ForceScreenFilter","False",},
{[PSU:     326: 1]  "ForceScreenFilterTo", / {"ForceScreenFilterTo","GcScreenFilters.xml",},
:[.SU:     327: 2]  | {"ScreenFilter","Solarise",},
:[   :     328: 1]  <<< }
{[PSU:     329: 1]  "ForceBiomeSubTypeTo", / {"ForceBiomeSubTypeTo","GcBiomeSubType.xml",},
:[.SU:     330: 2]  | {"BiomeSubType","None",},
:[   :     331: 1]  <<< }
:[.su:     332: 1]  {"ForceBuildingRace","False",},
{[PSU:     333: 1]  "ForceBuildingRaceTo", / {"ForceBuildingRaceTo","GcAlienRace.xml",},
:[.S.:     334: 2]  | {"AlienRace","Traders",},
:[   :     335: 1]  <<< }
:[.su:     336: 1]  {"ForceLifeLevel","False",},
{[PSU:     337: 1]  "ForceLifeLevelTo", / {"ForceLifeLevelTo","GcPlanetLife.xml",},
:[.S.:     338: 2]  | {"LifeSetting","Full",},
:[   :     339: 1]  <<< }
:[.su:     340: 1]  {"ForceCreatureLifeLevel","False",},
:[.su:     341: 1]  {"ForceDefaultCreatureFile","False",},
:[.SU:     342: 1]  {"DefaultGroundCreatureTable","DEFAULT",},
:[.SU:     343: 1]  {"DefaultAirCreatureTable","DEFAULT",},
:[.SU:     344: 1]  {"DefaultWaterCreatureTable","DEFAULT",},
:[.SU:     345: 1]  {"DefaultCaveCreatureTable","DEFAULT",},
{[PSU:     346: 1]  "ForceCreatureLifeLevelTo", / {"ForceCreatureLifeLevelTo","GcPlanetLife.xml",},
:[.S.:     347: 2]  | {"LifeSetting","Full",},
:[   :     348: 1]  <<< }
{[PSU:     349: 1]  "ForceTerrainSettings", / {"ForceTerrainSettings","GcPlanetLife.xml",},
:[.S.:     350: 2]  | {"LifeSetting","Full",},
:[   :     351: 1]  <<< }
:[.su:     352: 1]  {"ForceTerrainType","False",},
{[PSU:     353: 1]  "ForceTerrainTypeTo", / {"ForceTerrainTypeTo","TkVoxelGeneratorSettingsTypes.xml",},
:[.SU:     354: 2]  | {"TerrainSettings","Alpine",},
:[   :     355: 1]  <<< }
:[.su:     356: 1]  {"ForcePrimeTerrain","False",},
:[.su:     357: 1]  {"ForceBinaryStar","False",},
:[.su:     358: 1]  {"ForceTernaryStar","False",},
{[PSU:     359: 1]  "ForceAnomalyTo", / {"ForceAnomalyTo","GcGalaxyStarAnomaly.xml",},
:[.SU:     360: 2]  | {"GalaxyStarAnomaly","None",},
:[   :     361: 1]  <<< }
:[.su:     362: 1]  {"ForcePlanetsToHaveWater","False",},
:[.su:     363: 1]  {"ForceWaterObjectFileIndex","-1",},
:[.su:     364: 1]  {"ForceSkyColourIndex","-1",},
:[.su:     365: 1]  {"ForceWaterColourIndex","-1",},
:[.su:     366: 1]  {"ForceGrassColourIndex","-1",},
:[.su:     367: 1]  {"ModifyPlanetsInInitialSystems","True",},
:[.su:     368: 1]  {"ForcePlanetsToHaveNoWater","False",},
:[.su:     369: 1]  {"ForcePlanetsToHaveNoCaves","False",},
:[.su:     370: 1]  {"ForcePlanetsToHaveNoNoiseLayers","False",},
:[.su:     371: 1]  {"ForcePlanetsToHaveNoTerrainFeatures","False",},
:[.su:     372: 1]  {"DisableLimits","False",},
:[.su:     373: 1]  {"LimitPerRegionInstances","True",},
:[.su:     374: 1]  {"LimitPerRegionBodies","True",},
:[.su:     375: 1]  {"LimitGlobalInstances","True",},
:[.su:     376: 1]  {"LimitGlobalBodies","False",},
:[.su:     377: 1]  {"GenerateFarLodBuildingDist","1000",},
:[.su:     378: 1]  {"DeferRegionBodies","True",},
:[.su:     379: 1]  {"GenerateCostDistance","0.5",},
:[.su:     380: 1]  {"GenerateCostAngle","-0.5",},
:[.su:     381: 1]  {"GenerateCostLOD","-0.5",},
:[.su:     382: 1]  {"GenerateCostWait","-0.1",},
:[.su:     383: 1]  {"DChecksEnabled","False",},
:[.su:     384: 1]  {"DChecksOutputJson","False",},
:[.su:     385: 1]  {"DChecksOutputBinary","False",},
:[.su:     386: 1]  {"DChecksOutputFileLine","False",},
:[.su:     387: 1]  {"FrameFlipRateDefault","1",},
:[.su:     388: 1]  {"FrameFlipRateLoad","1",},
:[.su:     389: 1]  {"FrameFlipRateGame","1",},
:[.su:     390: 1]  {"MaxFrameRate","150",},
:[.su:     391: 1]  {"DisableBaseBuilding","False",},
:[.su:     392: 1]  {"DisableBaseBuildingLimits","False",},
:[.su:     393: 1]  {"AllowGlobalPartSnapping","False",},
:[.su:     394: 1]  {"BaseDownloadTimeout","40",},
:[.su:     395: 1]  {"DisableBasePowerRequirements","False",},
:[.su:     396: 1]  {"EnableBaseMovingOption","False",},
:[.su:     397: 1]  {"MoveBaseIndex","0",},
{[PSU:     399: 1]  "AutomaticPartSpawnStyle", / {"AutomaticPartSpawnStyle","GcBaseBuildingPartStyle.xml",},
:[.SU:     400: 2]  | {"Style","None",},
:[   :     401: 1]  <<< }
:[.su:     402: 1]  {"AutomaticPartSpawnInactive","False",},
:[.su:     403: 1]  {"ProfilerPartIndexPhase","0",},
:[.su:     404: 1]  {"ProfilerPartIndexStride","1",},
:[.su:     405: 1]  {"ProfilerPartIteration","0",},
:[.su:     406: 1]  {"BaseAdmin","False",},
:[.SU:     407: 1]  {"BaseServerPlatform","pc",},
:[.su:     408: 1]  {"BasePayloadMultiplier","3",},
:[.su:     409: 1]  {"CrossPlatformFeaturedBases","True",},
:[.su:     410: 1]  {"ShowMissionIdInTitle","False",},
{[PSU:     411: 1]  "ToolkitGlobals", / {"ToolkitGlobals","TkGlobals.xml",},
:[.SU:     412: 2]  | {"AssertsLevel","Enabled",},
:[.su:     413: 2]  | {"DefaultSelectIgnoreAsserts","False",},
:[.SU:     414: 2]  | {"EnabledChannels","Default, Note, Error, Warning, Info, Alt, AltWarn, AltError",},
:[.su:     417: 2]  | {"LoadBalanceTimeoutMS","25",},
:[.su:     418: 2]  | {"VRLoadBalanceTimeoutMS","9",},
:[.su:     419: 2]  | {"LogInputSetup","False",},
:[.su:     420: 2]  | {"LogInputChanges","False",},
:[.su:     421: 2]  | {"DisableResScaling","False",},
:[.su:     422: 2]  | {"WwiseVibrationMultiplierPrimary","1",},
:[.su:     423: 2]  | {"WwiseVibrationMultiplierSecondary","0.4",},
:[   :     424: 1]  <<< }
:[.su:     425: 1]  {"AllowOverrideSettlementOwnership","False",},
:[.su:     428: 1]  {"BlockSettlementsNetwork","False",},
:[.su:     429: 1]  {"EnableAccessibleUI","False",},
:[   :     430: 0]/Data } --Do not use, NOT a KEYWORD
 TYPE:FILELINE:LEVEL     KEYWORDS
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
>>> MapFileTree: GCDEBUGOPTIONS.GLOBAL.EXML (NMSARC.59B126E2.pak) "2022/03/16-18:47:55"
