>>> MapFileTree: MODELS\COMMON\SPACECRAFT\SAILSHIP\SAILSHIPPARTS\SAILSHIPANIMS\SAILSHIP_SHARED\ENTITIES\ROOTJNT.ENTITY.EXML (NMSARC.515F1D3.pak) "2022/05/04-23:29:26"
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 TYPE:FILELINE:LEVEL     KEYWORDS
{[   :       3: 0]TkAttachmentData --Do not use, NOT a KEYWORD
{[P..:       4: 1]  "Components",
{[P..:       5: 2]  | "TkAnimationComponentData.xml",
{[PSU:       6: 3]  | | "Idle", / {"Idle","TkAnimationData.xml",},
:[.SU:       8: 4]  | | | {"Filename","MODELS/COMMON/SPACECRAFT/SAILSHIP/SAILSHIP_PROC.ANIM.MBIN",},
:[.S.:       9: 4]  | | | {"AnimType","OneShotBlendable",},
:[.s.:      10: 4]  | | | {"FrameStart","0",},
:[.s.:      11: 4]  | | | {"FrameEnd","0",},
:[.s.:      14: 4]  | | | {"Priority","0",},
:[.s.:      15: 4]  | | | {"OffsetMin","0",},
:[.s.:      16: 4]  | | | {"OffsetMax","0",},
:[.s.:      17: 4]  | | | {"Delay","0",},
:[.s.:      18: 4]  | | | {"Speed","1",},
:[.s.:      19: 4]  | | | {"ActionStartFrame","0",},
:[.s.:      20: 4]  | | | {"ActionFrame","-1",},
:[.S.:      21: 4]  | | | {"CreatureSize","AllSizes",},
:[.s.:      22: 4]  | | | {"Additive","False",},
:[.s.:      23: 4]  | | | {"Mirrored","False",},
:[.s.:      24: 4]  | | | {"Active","True",},
:[.s.:      26: 4]  | | | {"AdditiveBaseFrame","0",},
{[PS.:      27: 4]  | | | "GameData", / {"GameData","TkAnimationGameData.xml",},
:[.s.:      28: 5]  | | | | {"RootMotionEnabled","False",},
:[.s.:      29: 5]  | | | | {"BlockPlayerMovement","False",},
:[.S.:      30: 5]  | | | | {"BlockPlayerWeapon","Unblocked",},
:[   :      31: 4]  | | | <<< }
:[   :      32: 3]  | | <<< }
{[P..:      33: 3]  | | "Anims",
{[P..:      34: 4]  | | | "TkAnimationData.xml",
:[.SU:      35: 5]  | | | | {"Anim","TAKEOFF",},
:[.SU:      36: 5]  | | | | {"Filename","MODELS/COMMON/SPACECRAFT/SAILSHIP/SAILSHIPPARTS/SAILSHIPANIMS/SAILSHIP_TAKEOFF.ANIM.MBIN",},
:[.S.:      37: 5]  | | | | {"AnimType","OneShotBlendable",},
:[.s.:      38: 5]  | | | | {"FrameStart","0",},
:[.su:      39: 5]  | | | | {"FrameEnd","472",},
:[.s.:      42: 5]  | | | | {"Priority","0",},
:[.s.:      43: 5]  | | | | {"OffsetMin","0",},
:[.s.:      44: 5]  | | | | {"OffsetMax","0",},
:[.s.:      45: 5]  | | | | {"Delay","0",},
:[.s.:      46: 5]  | | | | {"Speed","1",},
:[.s.:      47: 5]  | | | | {"ActionStartFrame","0",},
:[.s.:      48: 5]  | | | | {"ActionFrame","-1",},
:[.S.:      49: 5]  | | | | {"CreatureSize","AllSizes",},
:[.s.:      50: 5]  | | | | {"Additive","False",},
:[.s.:      51: 5]  | | | | {"Mirrored","False",},
:[.s.:      52: 5]  | | | | {"Active","False",},
:[.s.:      54: 5]  | | | | {"AdditiveBaseFrame","0",},
{[PS.:      55: 5]  | | | | "GameData", / {"GameData","TkAnimationGameData.xml",},
:[.s.:      56: 6]  | | | | | {"RootMotionEnabled","False",},
:[.s.:      57: 6]  | | | | | {"BlockPlayerMovement","False",},
:[.S.:      58: 6]  | | | | | {"BlockPlayerWeapon","Unblocked",},
:[   :      59: 5]  | | | | <<< }
:[   :      60: 4]  | | | <<< }
{[P..:      61: 4]  | | | "TkAnimationData.xml",
:[.SU:      62: 5]  | | | | {"Anim","LANDING",},
:[.SU:      63: 5]  | | | | {"Filename","MODELS/COMMON/SPACECRAFT/SAILSHIP/SAILSHIPPARTS/SAILSHIPANIMS/SAILSHIP_LANDING.ANIM.MBIN",},
:[.S.:      64: 5]  | | | | {"AnimType","OneShotBlendable",},
:[.s.:      65: 5]  | | | | {"FrameStart","0",},
:[.su:      66: 5]  | | | | {"FrameEnd","240",},
:[.s.:      69: 5]  | | | | {"Priority","0",},
:[.s.:      70: 5]  | | | | {"OffsetMin","0",},
:[.s.:      71: 5]  | | | | {"OffsetMax","0",},
:[.s.:      72: 5]  | | | | {"Delay","0",},
:[.s.:      73: 5]  | | | | {"Speed","1",},
:[.s.:      74: 5]  | | | | {"ActionStartFrame","0",},
:[.s.:      75: 5]  | | | | {"ActionFrame","-1",},
:[.S.:      76: 5]  | | | | {"CreatureSize","AllSizes",},
:[.s.:      77: 5]  | | | | {"Additive","False",},
:[.s.:      78: 5]  | | | | {"Mirrored","False",},
:[.s.:      79: 5]  | | | | {"Active","False",},
:[.s.:      81: 5]  | | | | {"AdditiveBaseFrame","0",},
{[PS.:      82: 5]  | | | | "GameData", / {"GameData","TkAnimationGameData.xml",},
:[.s.:      83: 6]  | | | | | {"RootMotionEnabled","False",},
:[.s.:      84: 6]  | | | | | {"BlockPlayerMovement","False",},
:[.S.:      85: 6]  | | | | | {"BlockPlayerWeapon","Unblocked",},
:[   :      86: 5]  | | | | <<< }
:[   :      87: 4]  | | | <<< }
{[P..:      88: 4]  | | | "TkAnimationData.xml",
:[.SU:      89: 5]  | | | | {"Anim","LOWALTITUDE",},
:[.SU:      90: 5]  | | | | {"Filename","MODELS/COMMON/SPACECRAFT/SAILSHIP/SAILSHIPPARTS/SAILSHIPANIMS/SAILSHIP_SAILSUNFOLD.ANIM.MBIN",},
:[.S.:      91: 5]  | | | | {"AnimType","Control",},
:[.s.:      92: 5]  | | | | {"FrameStart","0",},
:[.s.:      93: 5]  | | | | {"FrameEnd","0",},
:[.SU:      94: 5]  | | | | {"StartNode","LWingJetTip_JNT",},
{[P..:      95: 5]  | | | | "ExtraStartNodes",
{[P..:      96: 6]  | | | | | "NMSString0x40.xml",
:[.SU:      97: 7]  | | | | | | {"Value","RWingJetTip_JNT",},
:[   :      98: 6]  | | | | | <<< }
:[   :      99: 5]  | | | | <<< }
:[.su:     100: 5]  | | | | {"Priority","1",},
:[.s.:     101: 5]  | | | | {"OffsetMin","0",},
:[.s.:     102: 5]  | | | | {"OffsetMax","0",},
:[.s.:     103: 5]  | | | | {"Delay","0",},
:[.s.:     104: 5]  | | | | {"Speed","1",},
:[.s.:     105: 5]  | | | | {"ActionStartFrame","0",},
:[.s.:     106: 5]  | | | | {"ActionFrame","-1",},
:[.S.:     107: 5]  | | | | {"CreatureSize","AllSizes",},
:[.s.:     108: 5]  | | | | {"Additive","False",},
:[.s.:     109: 5]  | | | | {"Mirrored","False",},
:[.s.:     110: 5]  | | | | {"Active","True",},
:[.SU:     111: 5]  | | | | {"AdditiveBaseAnim","LOWALTITUDE",},
:[.s.:     112: 5]  | | | | {"AdditiveBaseFrame","0",},
{[PS.:     113: 5]  | | | | "GameData", / {"GameData","TkAnimationGameData.xml",},
:[.s.:     114: 6]  | | | | | {"RootMotionEnabled","False",},
:[.s.:     115: 6]  | | | | | {"BlockPlayerMovement","False",},
:[.S.:     116: 6]  | | | | | {"BlockPlayerWeapon","Unblocked",},
:[   :     117: 5]  | | | | <<< }
:[   :     118: 4]  | | | <<< }
{[P..:     119: 4]  | | | "TkAnimationData.xml",
:[.SU:     120: 5]  | | | | {"Anim","TURNLEFT",},
:[.S.:     121: 5]  | | | | {"Filename","MODELS/COMMON/SPACECRAFT/SAILSHIP/SAILSHIPPARTS/SAILSHIPANIMS/SAILSHIP_TUCKIN.ANIM.MBIN",},
:[.S.:     122: 5]  | | | | {"AnimType","Control",},
:[.s.:     123: 5]  | | | | {"FrameStart","0",},
:[.s.:     124: 5]  | | | | {"FrameEnd","34",},
:[.s.:     127: 5]  | | | | {"Priority","2",},
:[.s.:     128: 5]  | | | | {"OffsetMin","0",},
:[.s.:     129: 5]  | | | | {"OffsetMax","0",},
:[.s.:     130: 5]  | | | | {"Delay","0",},
:[.s.:     131: 5]  | | | | {"Speed","1",},
:[.s.:     132: 5]  | | | | {"ActionStartFrame","0",},
:[.s.:     133: 5]  | | | | {"ActionFrame","-1",},
:[.S.:     134: 5]  | | | | {"CreatureSize","AllSizes",},
:[.s.:     135: 5]  | | | | {"Additive","True",},
:[.s.:     136: 5]  | | | | {"Mirrored","False",},
:[.s.:     137: 5]  | | | | {"Active","True",},
:[.SU:     138: 5]  | | | | {"AdditiveBaseAnim","TURNLEFT",},
:[.s.:     139: 5]  | | | | {"AdditiveBaseFrame","0",},
{[PS.:     140: 5]  | | | | "GameData", / {"GameData","TkAnimationGameData.xml",},
:[.s.:     141: 6]  | | | | | {"RootMotionEnabled","False",},
:[.s.:     142: 6]  | | | | | {"BlockPlayerMovement","False",},
:[.S.:     143: 6]  | | | | | {"BlockPlayerWeapon","Unblocked",},
:[   :     144: 5]  | | | | <<< }
:[   :     145: 4]  | | | <<< }
{[P..:     146: 4]  | | | "TkAnimationData.xml",
:[.SU:     147: 5]  | | | | {"Anim","TURNRIGHT",},
:[.S.:     148: 5]  | | | | {"Filename","MODELS/COMMON/SPACECRAFT/SAILSHIP/SAILSHIPPARTS/SAILSHIPANIMS/SAILSHIP_TUCKIN.ANIM.MBIN",},
:[.S.:     149: 5]  | | | | {"AnimType","Control",},
:[.s.:     150: 5]  | | | | {"FrameStart","0",},
:[.s.:     151: 5]  | | | | {"FrameEnd","34",},
:[.s.:     154: 5]  | | | | {"Priority","2",},
:[.s.:     155: 5]  | | | | {"OffsetMin","0",},
:[.s.:     156: 5]  | | | | {"OffsetMax","0",},
:[.s.:     157: 5]  | | | | {"Delay","0",},
:[.s.:     158: 5]  | | | | {"Speed","1",},
:[.s.:     159: 5]  | | | | {"ActionStartFrame","0",},
:[.s.:     160: 5]  | | | | {"ActionFrame","-1",},
:[.S.:     161: 5]  | | | | {"CreatureSize","AllSizes",},
:[.s.:     162: 5]  | | | | {"Additive","True",},
:[.s.:     163: 5]  | | | | {"Mirrored","False",},
:[.s.:     164: 5]  | | | | {"Active","True",},
:[.SU:     165: 5]  | | | | {"AdditiveBaseAnim","TURNRIGHT",},
:[.s.:     166: 5]  | | | | {"AdditiveBaseFrame","0",},
{[PS.:     167: 5]  | | | | "GameData", / {"GameData","TkAnimationGameData.xml",},
:[.s.:     168: 6]  | | | | | {"RootMotionEnabled","False",},
:[.s.:     169: 6]  | | | | | {"BlockPlayerMovement","False",},
:[.S.:     170: 6]  | | | | | {"BlockPlayerWeapon","Unblocked",},
:[   :     171: 5]  | | | | <<< }
:[   :     172: 4]  | | | <<< }
:[   :     173: 3]  | | <<< }
:[.su:     175: 3]  | | {"NetSyncAnimation","False",},
:[   :     177: 2]  | <<< }
{[P..:     178: 2]  | "GcTriggerActionComponentData.xml",
:[.su:     179: 3]  | | {"HideModel","False",},
:[.su:     180: 3]  | | {"StartInactive","False",},
{[P..:     181: 3]  | | "States",
{[P..:     182: 4]  | | | "GcActionTriggerState.xml",
:[.SU:     183: 5]  | | | | {"StateID","BOOT",},
:[   :     185: 4]  | | | <<< }
{[P..:     186: 4]  | | | "GcActionTriggerState.xml",
:[.SU:     187: 5]  | | | | {"StateID","LANDING",},
{[P..:     188: 5]  | | | | "Triggers",
{[P..:     189: 6]  | | | | | "GcActionTrigger.xml",
{[PS.:     190: 7]  | | | | | | "Event", / {"Event","GcStateTimeEvent.xml",},
:[.s.:     191: 8]  | | | | | | | {"Seconds","0",},
:[.s.:     192: 8]  | | | | | | | {"RandomSeconds","0",},
:[.s.:     193: 8]  | | | | | | | {"UseMissionClock","False",},
:[   :     194: 7]  | | | | | | <<< }
{[P..:     195: 7]  | | | | | | "Action",
{[P..:     196: 8]  | | | | | | | "GcPlayAudioAction.xml",
:[.SU:     197: 9]  | | | | | | | | {"Sound","Ship_Pirate_Landing_Wings",},
:[.s.:     198: 9]  | | | | | | | | {"UseOcclusion","False",},
:[.s.:     199: 9]  | | | | | | | | {"OcclusionRadius","2",},
:[   :     200: 8]  | | | | | | | <<< }
{[P..:     201: 8]  | | | | | | | "GcNodeActivationAction.xml",
:[.S.:     202: 9]  | | | | | | | | {"NodeActiveState","Activate",},
:[.S.:     203: 9]  | | | | | | | | {"Name","landinggear",},
:[.s.:     205: 9]  | | | | | | | | {"IncludePhysics","False",},
:[.s.:     206: 9]  | | | | | | | | {"IncludeChildPhysics","False",},
:[.s.:     207: 9]  | | | | | | | | {"NotifyNPC","False",},
:[.s.:     208: 9]  | | | | | | | | {"UseMasterModel","True",},
:[.s.:     209: 9]  | | | | | | | | {"UseLocalNode","False",},
:[.s.:     210: 9]  | | | | | | | | {"RestartEmitters","False",},
:[.s.:     211: 9]  | | | | | | | | {"AffectModels","False",},
:[   :     212: 8]  | | | | | | | <<< }
:[   :     213: 7]  | | | | | | <<< }
:[   :     214: 6]  | | | | | <<< }
:[   :     215: 5]  | | | | <<< }
:[   :     216: 4]  | | | <<< }
{[P..:     217: 4]  | | | "GcActionTriggerState.xml",
:[.SU:     218: 5]  | | | | {"StateID","TAKEOFF",},
{[P..:     219: 5]  | | | | "Triggers",
{[P..:     220: 6]  | | | | | "GcActionTrigger.xml",
{[PS.:     221: 7]  | | | | | | "Event", / {"Event","GcStateTimeEvent.xml",},
:[.s.:     222: 8]  | | | | | | | {"Seconds","0",},
:[.s.:     223: 8]  | | | | | | | {"RandomSeconds","0",},
:[.s.:     224: 8]  | | | | | | | {"UseMissionClock","False",},
:[   :     225: 7]  | | | | | | <<< }
{[P..:     226: 7]  | | | | | | "Action",
{[P..:     227: 8]  | | | | | | | "GcPlayAudioAction.xml",
:[.SU:     228: 9]  | | | | | | | | {"Sound","Ship_Pirate_TakeOff_Wings",},
:[.s.:     229: 9]  | | | | | | | | {"UseOcclusion","False",},
:[.s.:     230: 9]  | | | | | | | | {"OcclusionRadius","2",},
:[   :     231: 8]  | | | | | | | <<< }
{[P..:     232: 8]  | | | | | | | "GcNodeActivationAction.xml",
:[.S.:     233: 9]  | | | | | | | | {"NodeActiveState","Activate",},
:[.S.:     234: 9]  | | | | | | | | {"Name","landinggear",},
:[.s.:     236: 9]  | | | | | | | | {"IncludePhysics","False",},
:[.s.:     237: 9]  | | | | | | | | {"IncludeChildPhysics","False",},
:[.s.:     238: 9]  | | | | | | | | {"NotifyNPC","False",},
:[.s.:     239: 9]  | | | | | | | | {"UseMasterModel","True",},
:[.s.:     240: 9]  | | | | | | | | {"UseLocalNode","False",},
:[.s.:     241: 9]  | | | | | | | | {"RestartEmitters","False",},
:[.s.:     242: 9]  | | | | | | | | {"AffectModels","False",},
:[   :     243: 8]  | | | | | | | <<< }
:[   :     244: 7]  | | | | | | <<< }
:[   :     245: 6]  | | | | | <<< }
:[   :     246: 5]  | | | | <<< }
:[   :     247: 4]  | | | <<< }
{[P..:     248: 4]  | | | "GcActionTriggerState.xml",
:[.SU:     249: 5]  | | | | {"StateID","TURNLEFT",},
:[   :     251: 4]  | | | <<< }
{[P..:     252: 4]  | | | "GcActionTriggerState.xml",
:[.SU:     253: 5]  | | | | {"StateID","TURNRIGHT",},
:[   :     255: 4]  | | | <<< }
:[   :     256: 3]  | | <<< }
:[.su:     257: 3]  | | {"Persistent","False",},
:[.su:     259: 3]  | | {"ResetShotTimeOnStateChange","False",},
:[.su:     260: 3]  | | {"LinkStateToBaseGrid","False",},
:[   :     261: 2]  | <<< }
:[   :     262: 1]  <<< }
{[P..:     263: 1]  "LodDistances",
:[   :     269: 1]  <<< }
:[   :     270: 0]/Data } --Do not use, NOT a KEYWORD
 TYPE:FILELINE:LEVEL     KEYWORDS
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
>>> MapFileTree: MODELS\COMMON\SPACECRAFT\SAILSHIP\SAILSHIPPARTS\SAILSHIPANIMS\SAILSHIP_SHARED\ENTITIES\ROOTJNT.ENTITY.EXML (NMSARC.515F1D3.pak) "2022/05/04-23:29:26"
