>>> MapFileTree: MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\CRATE\CRATE_LARGE_RARE\ENTITIES\CRATE_LARGE_RARE.ENTITY.EXML (NMSARC.515F1D3.pak) "2022/05/04-23:29:25"
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 TYPE:FILELINE:LEVEL     KEYWORDS
{[   :       3: 0]TkAttachmentData --Do not use, NOT a KEYWORD
{[P..:       4: 1]  "Components",
{[P..:       5: 2]  | "TkPhysicsComponentData.xml",
{[PSU:       6: 3]  | | "Data", / {"Data","TkPhysicsData.xml",},
:[.su:       7: 4]  | | | {"Mass","0",},
:[.su:       8: 4]  | | | {"Friction","0.5",},
:[.su:       9: 4]  | | | {"RollingFriction","0.2",},
:[.su:      10: 4]  | | | {"AngularDamping","0.2",},
:[.su:      11: 4]  | | | {"LinearDamping","0.1",},
:[.s.:      12: 4]  | | | {"Gravity","20",},
:[   :      13: 3]  | | <<< }
{[PSU:      14: 3]  | | "RagdollData", / {"RagdollData","TkRagdollData.xml",},
:[.su:      15: 4]  | | | {"Density","1",},
:[.s.:      16: 4]  | | | {"Gravity","20",},
:[   :      19: 3]  | | <<< }
{[PSU:      20: 3]  | | "TriggerVolumeType", / {"TriggerVolumeType","TkVolumeTriggerType.xml",},
:[.SU:      21: 4]  | | | {"VolumeTriggerType","Open",},
:[   :      22: 3]  | | <<< }
:[.SU:      23: 3]  | | {"SurfaceProperties","None",},
:[.su:      24: 3]  | | {"TriggerVolume","False",},
:[.su:      25: 3]  | | {"Climbable","False",},
:[.su:      26: 3]  | | {"Floor","False",},
:[.su:      27: 3]  | | {"IgnoreModelOwner","False",},
:[.su:      28: 3]  | | {"NoVehicleCollide","False",},
:[.su:      29: 3]  | | {"NoPlayerCollide","False",},
:[.su:      30: 3]  | | {"CameraInvisible","False",},
:[.su:      31: 3]  | | {"InvisibleForInteraction","False",},
:[.su:      32: 3]  | | {"AllowTeleporter","False",},
:[.su:      33: 3]  | | {"BlockTeleporter","False",},
:[.su:      34: 3]  | | {"DisableGravity","False",},
:[.su:      35: 3]  | | {"SpinOnCreate","0",},
:[.su:      36: 3]  | | {"UseBasePartOptimisation","False",},
:[   :      37: 2]  | <<< }
{[P..:      38: 2]  | "GcSimpleInteractionComponentData.xml",
:[.SU:      39: 3]  | | {"SimpleInteractionType","Treasure",},
:[.su:      40: 3]  | | {"InteractDistance","0",},
:[.su:      41: 3]  | | {"Use2dInteractDistance","False",},
:[.SU:      42: 3]  | | {"Id","CRATE",},
{[PSU:      43: 3]  | | "Rarity", / {"Rarity","GcRarity.xml",},
:[.SU:      44: 4]  | | | {"Rarity","Rare",},
:[   :      45: 3]  | | <<< }
{[PSU:      46: 3]  | | "Size", / {"Size","GcSizeIndicator.xml",},
:[.SU:      47: 4]  | | | {"SizeIndicator","Large",},
:[   :      48: 3]  | | <<< }
:[.SU:      49: 3]  | | {"TriggerAction","INACTIVE",},
:[.su:      52: 3]  | | {"BroadcastTriggerAction","False",},
:[.su:      53: 3]  | | {"Delay","0.6",},
:[.su:      54: 3]  | | {"HideContents","True",},
:[.su:      55: 3]  | | {"InteractIsCrime","False",},
{[PSU:      56: 3]  | | "InteractFiendCrimeType", / {"InteractFiendCrimeType","GcFiendCrime.xml",},
:[.SU:      57: 4]  | | | {"FiendCrime","None",},
:[   :      58: 3]  | | <<< }
:[.su:      59: 3]  | | {"InteractFiendCrimeChance","1",},
:[.su:      60: 3]  | | {"InteractCrimeLevel","0",},
:[.su:      61: 3]  | | {"NotifyEncounter","False",},
{[PSU:      62: 3]  | | "ActivationCost", / {"ActivationCost","GcInteractionActivationCost.xml",},
:[.su:      65: 4]  | | | {"Cost","0",},
:[.su:      66: 4]  | | | {"Repeat","False",},
:[   :      68: 3]  | | <<< }
{[PSU:      69: 3]  | | "StatToTrack", / {"StatToTrack","GcStatsEnum.xml",},
:[.SU:      70: 4]  | | | {"GcStatEnum","None",},
:[   :      71: 3]  | | <<< }
:[.su:      72: 3]  | | {"StartsBuried","False",},
:[.su:      73: 3]  | | {"MustBeVisibleToInteract","False",},
:[.su:      74: 3]  | | {"NeedsStorm","False",},
:[.SU:      75: 3]  | | {"Name","BLD_LOCKBOX_NAME_L",},
:[.SU:      78: 3]  | | {"ScanType","BINOC_INTERACTABLE",},
{[PSU:      80: 3]  | | "ScanIcon", / {"ScanIcon","GcDiscoveryTypes.xml",},
:[.SU:      81: 4]  | | | {"DiscoveryType","Unknown",},
:[   :      82: 3]  | | <<< }
:[.su:      83: 3]  | | {"ActivateLocatorsFromRarity","False",},
{[P..:      84: 3]  | | "RarityLocators",
{[PSU:      85: 4]  | | | "Common", / {"Common","NMSString0x10.xml",},
:[   :      87: 4]  | | | <<< }
{[PSU:      88: 4]  | | | "Uncommon", / {"Uncommon","NMSString0x10.xml",},
:[   :      90: 4]  | | | <<< }
{[PSU:      91: 4]  | | | "Rare", / {"Rare","NMSString0x10.xml",},
:[   :      93: 4]  | | | <<< }
:[   :      94: 3]  | | <<< }
{[P..:      96: 3]  | | "RewardOverrideTable",
{[P..:      97: 4]  | | | "GcRewardMissionOverride.xml",
:[.SU:      98: 5]  | | | | {"Mission","TUT_NEXT1",},
:[.SU:      99: 5]  | | | | {"Reward","TUT_GOODS",},
:[   :     100: 4]  | | | <<< }
:[   :     101: 3]  | | <<< }
:[.su:     103: 3]  | | {"UsePersonalPersistentBuffer","False",},
:[.su:     104: 3]  | | {"ReseedOnRewardSuccess","False",},
:[.su:     105: 3]  | | {"CanCollectInMech","False",},
:[   :     106: 2]  | <<< }
{[P..:     107: 2]  | "GcScannableComponentData.xml",
:[.su:     108: 3]  | | {"ScanRange","200",},
:[.SU:     109: 3]  | | {"ScanName","SCAN_CARGO_DROP",},
:[.su:     110: 3]  | | {"ScanTime","30",},
:[.su:     111: 3]  | | {"CompassRangeMultiplier","0.25",},
:[.su:     112: 3]  | | {"AlwaysShowRange","0",},
:[.su:     113: 3]  | | {"CanTagIcon","True",},
:[.su:     114: 3]  | | {"ClearTagOnArrival","True",},
:[.su:     115: 3]  | | {"DisableIfBuildingPart","False",},
:[.su:     116: 3]  | | {"DisableIfInBase","False",},
:[.su:     117: 3]  | | {"UseModelNode","True",},
{[PSU:     118: 3]  | | "Icon", / {"Icon","GcScannerIconTypes.xml",},
:[.SU:     119: 4]  | | | {"ScanIconType","Crate",},
:[   :     120: 3]  | | <<< }
:[.SU:     121: 3]  | | {"ScannableType","Binoculars",},
:[.su:     122: 3]  | | {"IsPlacedMarker","False",},
:[.su:     123: 3]  | | {"ShowInFreighterBranchRoom","False",},
:[.su:     124: 3]  | | {"TellPlayerIfFreighterObjectUsed","False",},
:[.SU:     125: 3]  | | {"FreighterObjectAlreadyUsedLocID","UI_ABAND_LOG_READ",},
:[.su:     126: 3]  | | {"AllowedToMerge","True",},
:[.su:     128: 3]  | | {"MinDisplayDistanceOverride","-1",},
:[   :     129: 2]  | <<< }
{[P..:     130: 2]  | "TkAnimationComponentData.xml",
{[PSU:     131: 3]  | | "Idle", / {"Idle","TkAnimationData.xml",},
:[.SU:     134: 4]  | | | {"AnimType","Loop",},
:[.s.:     135: 4]  | | | {"FrameStart","0",},
:[.su:     136: 4]  | | | {"FrameEnd","0",},
:[.s.:     139: 4]  | | | {"Priority","0",},
:[.s.:     140: 4]  | | | {"OffsetMin","0",},
:[.s.:     141: 4]  | | | {"OffsetMax","0",},
:[.s.:     142: 4]  | | | {"Delay","0",},
:[.s.:     143: 4]  | | | {"Speed","1",},
:[.s.:     144: 4]  | | | {"ActionStartFrame","0",},
:[.s.:     145: 4]  | | | {"ActionFrame","-1",},
:[.S.:     146: 4]  | | | {"CreatureSize","AllSizes",},
:[.s.:     147: 4]  | | | {"Additive","False",},
:[.s.:     148: 4]  | | | {"Mirrored","False",},
:[.su:     149: 4]  | | | {"Active","True",},
:[.s.:     151: 4]  | | | {"AdditiveBaseFrame","0",},
{[PS.:     152: 4]  | | | "GameData", / {"GameData","TkAnimationGameData.xml",},
:[.s.:     153: 5]  | | | | {"RootMotionEnabled","False",},
:[.s.:     154: 5]  | | | | {"BlockPlayerMovement","False",},
:[.S.:     155: 5]  | | | | {"BlockPlayerWeapon","Unblocked",},
:[   :     156: 4]  | | | <<< }
:[   :     157: 3]  | | <<< }
{[P..:     158: 3]  | | "Anims",
{[P..:     159: 4]  | | | "TkAnimationData.xml",
:[.S.:     160: 5]  | | | | {"Anim","OPEN",},
:[.SU:     161: 5]  | | | | {"Filename","MODELS/PLANETS/BIOMES/COMMON/BUILDINGS/CRATE/ANIMS/CRATE_LARGE_RARE_OPEN.ANIM.MBIN",},
:[.SU:     162: 5]  | | | | {"AnimType","OneShotBlendable",},
:[.s.:     163: 5]  | | | | {"FrameStart","0",},
:[.su:     164: 5]  | | | | {"FrameEnd","70",},
:[.s.:     167: 5]  | | | | {"Priority","0",},
:[.s.:     168: 5]  | | | | {"OffsetMin","0",},
:[.s.:     169: 5]  | | | | {"OffsetMax","0",},
:[.s.:     170: 5]  | | | | {"Delay","0",},
:[.s.:     171: 5]  | | | | {"Speed","1",},
:[.s.:     172: 5]  | | | | {"ActionStartFrame","0",},
:[.s.:     173: 5]  | | | | {"ActionFrame","-1",},
:[.S.:     174: 5]  | | | | {"CreatureSize","AllSizes",},
:[.s.:     175: 5]  | | | | {"Additive","False",},
:[.s.:     176: 5]  | | | | {"Mirrored","False",},
:[.su:     177: 5]  | | | | {"Active","False",},
:[.s.:     179: 5]  | | | | {"AdditiveBaseFrame","0",},
{[PS.:     180: 5]  | | | | "GameData", / {"GameData","TkAnimationGameData.xml",},
:[.s.:     181: 6]  | | | | | {"RootMotionEnabled","False",},
:[.s.:     182: 6]  | | | | | {"BlockPlayerMovement","False",},
:[.S.:     183: 6]  | | | | | {"BlockPlayerWeapon","Unblocked",},
:[   :     184: 5]  | | | | <<< }
:[   :     185: 4]  | | | <<< }
:[   :     186: 3]  | | <<< }
:[.su:     188: 3]  | | {"NetSyncAnimation","False",},
:[   :     190: 2]  | <<< }
{[P..:     191: 2]  | "GcTriggerActionComponentData.xml",
:[.su:     192: 3]  | | {"HideModel","False",},
:[.su:     193: 3]  | | {"StartInactive","False",},
{[P..:     194: 3]  | | "States",
{[P..:     195: 4]  | | | "GcActionTriggerState.xml",
:[.SU:     196: 5]  | | | | {"StateID","BOOT",},
:[   :     198: 4]  | | | <<< }
{[P..:     199: 4]  | | | "GcActionTriggerState.xml",
:[.SU:     200: 5]  | | | | {"StateID","MAINTDONE",},
{[P..:     201: 5]  | | | | "Triggers",
{[P..:     202: 6]  | | | | | "GcActionTrigger.xml",
{[PSU:     203: 7]  | | | | | | "Event", / {"Event","GcStateTimeEvent.xml",},
:[.su:     204: 8]  | | | | | | | {"Seconds","0",},
:[.su:     205: 8]  | | | | | | | {"RandomSeconds","0",},
:[.su:     206: 8]  | | | | | | | {"UseMissionClock","False",},
:[   :     207: 7]  | | | | | | <<< }
{[P..:     208: 7]  | | | | | | "Action",
{[P..:     209: 8]  | | | | | | | "GcPlayAudioAction.xml",
:[.SU:     210: 9]  | | | | | | | | {"Sound","Obj_Crate_Large",},
:[.su:     211: 9]  | | | | | | | | {"UseOcclusion","False",},
:[.su:     212: 9]  | | | | | | | | {"OcclusionRadius","2",},
:[   :     213: 8]  | | | | | | | <<< }
{[P..:     214: 8]  | | | | | | | "GcPlayAnimAction.xml",
:[.S.:     215: 9]  | | | | | | | | {"Anim","OPEN",},
:[   :     216: 8]  | | | | | | | <<< }
:[   :     217: 7]  | | | | | | <<< }
:[   :     218: 6]  | | | | | <<< }
:[   :     219: 5]  | | | | <<< }
:[   :     220: 4]  | | | <<< }
:[   :     221: 3]  | | <<< }
:[.su:     222: 3]  | | {"Persistent","False",},
:[.su:     224: 3]  | | {"ResetShotTimeOnStateChange","False",},
:[.su:     225: 3]  | | {"LinkStateToBaseGrid","False",},
:[   :     226: 2]  | <<< }
{[P..:     227: 2]  | "GcMaintenanceComponentData.xml",
{[P..:     228: 3]  | | "PreInstalledTech",
{[P..:     229: 4]  | | | "GcMaintenanceElement.xml",
{[PSU:     230: 5]  | | | | "ItemGroupOverride", / {"ItemGroupOverride","GcMaintenanceElementGroups.xml",},
:[.SU:     231: 6]  | | | | | {"MaintenanceGroup","Custom",},
:[   :     232: 5]  | | | | <<< }
{[PSU:     233: 5]  | | | | "Type", / {"Type","GcInventoryType.xml",},
:[.SU:     234: 6]  | | | | | {"InventoryType","Substance",},
:[   :     235: 5]  | | | | <<< }
:[.SU:     236: 5]  | | | | {"Id","SPACEGUNK3",},
:[.su:     237: 5]  | | | | {"MinRandAmount","50",},
:[.su:     238: 5]  | | | | {"MaxRandAmount","100",},
:[.su:     239: 5]  | | | | {"MaxCapactiy","-1",},
:[.su:     240: 5]  | | | | {"AmountEmptyTimePeriod","0",},
:[.SU:     241: 5]  | | | | {"UpdateType","UpdatesAlways",},
:[.su:     242: 5]  | | | | {"DamagedAfterTimePeriodMin","0",},
:[.su:     243: 5]  | | | | {"DamagedAfterTimePeriodMax","0",},
:[.SU:     244: 5]  | | | | {"DamageStatus","Damaged",},
:[.SU:     245: 5]  | | | | {"CompletionRequirement","EmptySlot",},
:[   :     246: 4]  | | | <<< }
:[   :     247: 3]  | | <<< }
:[.su:     248: 3]  | | {"VisibleMaintenanceSlots","-1",},
:[.su:     249: 3]  | | {"AllowRepair","False",},
:[.su:     250: 3]  | | {"AllowCharge","False",},
:[.su:     251: 3]  | | {"AllowDismantle","True",},
:[.su:     252: 3]  | | {"AllowInstallTech","False",},
:[.su:     253: 3]  | | {"AllowCraftProduct","False",},
:[.su:     254: 3]  | | {"AllowTransfer","True",},
:[.su:     255: 3]  | | {"AllowMoveAndStack","False",},
:[.su:     256: 3]  | | {"AllowTransferIn","False",},
:[.su:     257: 3]  | | {"AutoCompleteOnStart","False",},
:[.su:     258: 3]  | | {"UseModelResourceRenderer","False",},
:[.su:     259: 3]  | | {"UseBoundsForIconCentre","True",},
:[.SU:     260: 3]  | | {"Interactable","OnlyWhenNotComplete",},
:[.su:     261: 3]  | | {"ForceNoninteraction","False",},
:[.su:     262: 3]  | | {"CompletedTransitionDelay","2",},
:[.su:     263: 3]  | | {"ShareInteractionModelRender","True",},
{[PSU:     264: 3]  | | "ModelRendererData", / {"ModelRendererData","TkModelRendererData.xml",},
{[PS.:     265: 4]  | | | "Camera", / {"Camera","TkModelRendererCameraData.xml",},
:[.su:     266: 5]  | | | | {"Distance","3",},
{[PS.:     267: 5]  | | | | "Offset", / {"Offset","Vector3f.xml",},
:[.su:     268: 6]  | | | | | {"x","0.15",},
:[.su:     269: 6]  | | | | | {"y","0.5",},
:[.s.:     270: 6]  | | | | | {"z","0",},
:[   :     271: 5]  | | | | <<< }
:[.s.:     272: 5]  | | | | {"Roll","0",},
:[.su:     273: 5]  | | | | {"Pitch","31",},
:[.s.:     274: 5]  | | | | {"Rotate","0",},
:[.s.:     275: 5]  | | | | {"LightPitch","45",},
:[.s.:     276: 5]  | | | | {"LightRotate","45",},
{[PS.:     277: 5]  | | | | "Wander", / {"Wander","TkCameraWanderData.xml",},
:[.s.:     278: 6]  | | | | | {"CamWander","False",},
:[.s.:     279: 6]  | | | | | {"CamWanderPhase","0.003",},
:[.s.:     280: 6]  | | | | | {"CamWanderAmplitude","0.5",},
:[   :     281: 5]  | | | | <<< }
:[   :     282: 4]  | | | <<< }
:[.s.:     283: 4]  | | | {"Fov","30",},
:[.s.:     284: 4]  | | | {"AspectRatio","1.7777",},
:[.S.:     285: 4]  | | | {"ThumbnailMode","None",},
:[.S.:     286: 4]  | | | {"FocusType","ResourceBounds",},
{[PS.:     288: 4]  | | | "FocusOffset", / {"FocusOffset","Vector3f.xml",},
:[.s.:     289: 5]  | | | | {"x","0",},
:[.s.:     290: 5]  | | | | {"y","0",},
:[.s.:     291: 5]  | | | | {"z","0",},
:[   :     292: 4]  | | | <<< }
:[.s.:     293: 4]  | | | {"FocusInterpTime","0",},
:[.s.:     294: 4]  | | | {"BlendInTime","0.8",},
:[.s.:     295: 4]  | | | {"BlendInOffset","0",},
:[.s.:     297: 4]  | | | {"HeightOffset","0.005",},
:[.su:     298: 4]  | | | {"UsePlayerCameraInHmd","True",},
:[.s.:     299: 4]  | | | {"UseSensibleCameraFocusNodeIsNowOffsetNode","False",},
:[.s.:     300: 4]  | | | {"LookForFocusInMasterModel","False",},
:[   :     301: 3]  | | <<< }
{[PSU:     302: 3]  | | "ModelRendererDataAlt", / {"ModelRendererDataAlt","TkModelRendererData.xml",},
{[PS.:     303: 4]  | | | "Camera", / {"Camera","TkModelRendererCameraData.xml",},
:[.su:     304: 5]  | | | | {"Distance","2.25",},
{[PS.:     305: 5]  | | | | "Offset", / {"Offset","Vector3f.xml",},
:[.s.:     306: 6]  | | | | | {"x","0",},
:[.su:     307: 6]  | | | | | {"y","1.75",},
:[.s.:     308: 6]  | | | | | {"z","0",},
:[   :     309: 5]  | | | | <<< }
:[.s.:     310: 5]  | | | | {"Roll","0",},
:[.su:     311: 5]  | | | | {"Pitch","0",},
:[.s.:     312: 5]  | | | | {"Rotate","0",},
:[.s.:     313: 5]  | | | | {"LightPitch","45",},
:[.s.:     314: 5]  | | | | {"LightRotate","45",},
{[PS.:     315: 5]  | | | | "Wander", / {"Wander","TkCameraWanderData.xml",},
:[.s.:     316: 6]  | | | | | {"CamWander","False",},
:[.s.:     317: 6]  | | | | | {"CamWanderPhase","0.003",},
:[.s.:     318: 6]  | | | | | {"CamWanderAmplitude","0.5",},
:[   :     319: 5]  | | | | <<< }
:[   :     320: 4]  | | | <<< }
:[.s.:     321: 4]  | | | {"Fov","30",},
:[.s.:     322: 4]  | | | {"AspectRatio","1.7777",},
:[.S.:     323: 4]  | | | {"ThumbnailMode","None",},
:[.S.:     324: 4]  | | | {"FocusType","ResourceBounds",},
{[PS.:     326: 4]  | | | "FocusOffset", / {"FocusOffset","Vector3f.xml",},
:[.s.:     327: 5]  | | | | {"x","0",},
:[.s.:     328: 5]  | | | | {"y","0",},
:[.s.:     329: 5]  | | | | {"z","0",},
:[   :     330: 4]  | | | <<< }
:[.s.:     331: 4]  | | | {"FocusInterpTime","0",},
:[.s.:     332: 4]  | | | {"BlendInTime","0.8",},
:[.s.:     333: 4]  | | | {"BlendInOffset","0",},
:[.s.:     335: 4]  | | | {"HeightOffset","0.005",},
:[.su:     336: 4]  | | | {"UsePlayerCameraInHmd","False",},
:[.s.:     337: 4]  | | | {"UseSensibleCameraFocusNodeIsNowOffsetNode","False",},
:[.s.:     338: 4]  | | | {"LookForFocusInMasterModel","False",},
:[   :     339: 3]  | | <<< }
:[.SU:     340: 3]  | | {"ModelRendererResource","ModelNode",},
{[PSU:     341: 3]  | | "BroadcastLevel", / {"BroadcastLevel","GcBroadcastLevel.xml",},
:[.SU:     342: 4]  | | | {"BroadcastLevel","Scene",},
:[   :     343: 3]  | | <<< }
:[.SU:     345: 3]  | | {"Description","UI_MAINTAIN_CRATE_SUB",},
:[.SU:     346: 3]  | | {"ActionButtonOverride","REPAIR",},
:[.SU:     347: 3]  | | {"ActionDescriptionOverride","REPAIR_DESC",},
:[.SU:     348: 3]  | | {"ActionWarningOverride","WARN_TECH_DAMAGED",},
:[.su:     349: 3]  | | {"InWorldUIScaler","0",},
:[.su:     350: 3]  | | {"InteractionRequiresPower","False",},
:[   :     351: 2]  | <<< }
:[   :     352: 1]  <<< }
{[P..:     353: 1]  "LodDistances",
:[   :     359: 1]  <<< }
:[   :     360: 0]/Data } --Do not use, NOT a KEYWORD
 TYPE:FILELINE:LEVEL     KEYWORDS
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
>>> MapFileTree: MODELS\PLANETS\BIOMES\COMMON\BUILDINGS\CRATE\CRATE_LARGE_RARE\ENTITIES\CRATE_LARGE_RARE.ENTITY.EXML (NMSARC.515F1D3.pak) "2022/05/04-23:29:25"
