>>> MapFileTree: UI\COMPONENTS\INTERACTION\CINEMATICBARS.EXML (NMSARC.515F1D3.pak) "2022/03/16-18:34:38"
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 TYPE:FILELINE:LEVEL     KEYWORDS
{[   :       3: 0]GcNGuiLayerData --Do not use, NOT a KEYWORD
{[PS.:       4: 1]  "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.SU:       5: 2]  | {"ID","BARS",},
:[.s.:       7: 2]  | {"IsHidden","False",},
{[PS.:       8: 2]  | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.s.:       9: 3]  | | {"PositionX","0",},
:[.s.:      10: 3]  | | {"PositionY","0",},
:[.s.:      11: 3]  | | {"Width","100",},
:[.s.:      12: 3]  | | {"WidthPercentage","True",},
:[.su:      13: 3]  | | {"Height","100",},
:[.su:      14: 3]  | | {"HeightPercentage","True",},
:[.s.:      15: 3]  | | {"ConstrainProportions","False",},
:[.s.:      16: 3]  | | {"ConstrainAspect","1",},
:[.s.:      17: 3]  | | {"ForceAspect","False",},
:[.s.:      18: 3]  | | {"Anchor","True",},
:[.s.:      19: 3]  | | {"AnchorPercent","False",},
:[.s.:      20: 3]  | | {"SameLine","False",},
{[PS.:      21: 3]  | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:      22: 4]  | | | {"Vertical","Top",},
:[.S.:      23: 4]  | | | {"Horizontal","Left",},
:[   :      24: 3]  | | <<< }
:[.s.:      25: 3]  | | {"SlowCursorOnHover","False",},
:[.s.:      26: 3]  | | {"MaxWidth","0",},
:[   :      29: 2]  | <<< }
:[   :      30: 1]  <<< }
{[PS.:      31: 1]  "Style", / {"Style","TkNGuiGraphicStyle.xml",},
{[PS.:      32: 2]  | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:      33: 3]  | | {"PaddingX","0",},
:[.s.:      34: 3]  | | {"PaddingY","0",},
:[.s.:      35: 3]  | | {"MarginX","0",},
:[.s.:      36: 3]  | | {"MarginY","0",},
{[PS.:      37: 3]  | | "Colour", / {"Colour","Colour.xml",},
:[.s.:      38: 4]  | | | {"R","0",},
:[.s.:      39: 4]  | | | {"G","0",},
:[.s.:      40: 4]  | | | {"B","0",},
:[.s.:      41: 4]  | | | {"A","1",},
:[   :      42: 3]  | | <<< }
{[PS.:      43: 3]  | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:      44: 4]  | | | {"R","1",},
:[.s.:      45: 4]  | | | {"G","1",},
:[.s.:      46: 4]  | | | {"B","1",},
:[.s.:      47: 4]  | | | {"A","1",},
:[   :      48: 3]  | | <<< }
{[PS.:      49: 3]  | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:      50: 4]  | | | {"R","1",},
:[.s.:      51: 4]  | | | {"G","1",},
:[.s.:      52: 4]  | | | {"B","1",},
:[.s.:      53: 4]  | | | {"A","1",},
:[   :      54: 3]  | | <<< }
:[.S.:      55: 3]  | | {"Shape","Rectangle",},
:[.s.:      56: 3]  | | {"SolidColour","False",},
:[.s.:      57: 3]  | | {"HasDropShadow","False",},
:[.s.:      58: 3]  | | {"HasOuterGradient","False",},
:[.s.:      59: 3]  | | {"HasInnerGradient","False",},
:[.S.:      60: 3]  | | {"Gradient","None",},
:[.s.:      61: 3]  | | {"GradientStartOffset","0",},
:[.s.:      62: 3]  | | {"GradientEndOffset","0",},
:[.s.:      63: 3]  | | {"GradientOffsetPercent","False",},
{[PS.:      64: 3]  | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:      65: 4]  | | | {"R","0",},
:[.s.:      66: 4]  | | | {"G","0",},
:[.s.:      67: 4]  | | | {"B","0",},
:[.s.:      68: 4]  | | | {"A","1",},
:[   :      69: 3]  | | <<< }
:[.s.:      70: 3]  | | {"CornerRadius","0",},
:[.s.:      71: 3]  | | {"StrokeSize","0",},
:[.s.:      72: 3]  | | {"Image","0",},
:[.s.:      73: 3]  | | {"Icon","0",},
:[.s.:      74: 3]  | | {"StrokeGradient","False",},
:[.s.:      75: 3]  | | {"StrokeGradientOffset","0",},
:[.s.:      76: 3]  | | {"StrokeGradientFeather","0",},
{[PS.:      77: 3]  | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:      78: 4]  | | | {"R","1",},
:[.s.:      79: 4]  | | | {"G","1",},
:[.s.:      80: 4]  | | | {"B","1",},
:[.s.:      81: 4]  | | | {"A","1",},
:[   :      82: 3]  | | <<< }
:[   :      83: 2]  | <<< }
{[PS.:      84: 2]  | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:      85: 3]  | | {"PaddingX","0",},
:[.s.:      86: 3]  | | {"PaddingY","0",},
:[.s.:      87: 3]  | | {"MarginX","0",},
:[.s.:      88: 3]  | | {"MarginY","0",},
{[PS.:      89: 3]  | | "Colour", / {"Colour","Colour.xml",},
:[.s.:      90: 4]  | | | {"R","0",},
:[.s.:      91: 4]  | | | {"G","0",},
:[.s.:      92: 4]  | | | {"B","0",},
:[.s.:      93: 4]  | | | {"A","1",},
:[   :      94: 3]  | | <<< }
{[PS.:      95: 3]  | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:      96: 4]  | | | {"R","1",},
:[.s.:      97: 4]  | | | {"G","1",},
:[.s.:      98: 4]  | | | {"B","1",},
:[.s.:      99: 4]  | | | {"A","1",},
:[   :     100: 3]  | | <<< }
{[PS.:     101: 3]  | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     102: 4]  | | | {"R","1",},
:[.s.:     103: 4]  | | | {"G","1",},
:[.s.:     104: 4]  | | | {"B","1",},
:[.s.:     105: 4]  | | | {"A","1",},
:[   :     106: 3]  | | <<< }
:[.S.:     107: 3]  | | {"Shape","Rectangle",},
:[.s.:     108: 3]  | | {"SolidColour","False",},
:[.s.:     109: 3]  | | {"HasDropShadow","False",},
:[.s.:     110: 3]  | | {"HasOuterGradient","False",},
:[.s.:     111: 3]  | | {"HasInnerGradient","False",},
:[.S.:     112: 3]  | | {"Gradient","None",},
:[.s.:     113: 3]  | | {"GradientStartOffset","0",},
:[.s.:     114: 3]  | | {"GradientEndOffset","0",},
:[.s.:     115: 3]  | | {"GradientOffsetPercent","False",},
{[PS.:     116: 3]  | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     117: 4]  | | | {"R","0",},
:[.s.:     118: 4]  | | | {"G","0",},
:[.s.:     119: 4]  | | | {"B","0",},
:[.s.:     120: 4]  | | | {"A","1",},
:[   :     121: 3]  | | <<< }
:[.s.:     122: 3]  | | {"CornerRadius","0",},
:[.s.:     123: 3]  | | {"StrokeSize","0",},
:[.s.:     124: 3]  | | {"Image","0",},
:[.s.:     125: 3]  | | {"Icon","0",},
:[.s.:     126: 3]  | | {"StrokeGradient","False",},
:[.s.:     127: 3]  | | {"StrokeGradientOffset","0",},
:[.s.:     128: 3]  | | {"StrokeGradientFeather","0",},
{[PS.:     129: 3]  | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     130: 4]  | | | {"R","1",},
:[.s.:     131: 4]  | | | {"G","1",},
:[.s.:     132: 4]  | | | {"B","1",},
:[.s.:     133: 4]  | | | {"A","1",},
:[   :     134: 3]  | | <<< }
:[   :     135: 2]  | <<< }
{[PS.:     136: 2]  | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:     137: 3]  | | {"PaddingX","0",},
:[.s.:     138: 3]  | | {"PaddingY","0",},
:[.s.:     139: 3]  | | {"MarginX","0",},
:[.s.:     140: 3]  | | {"MarginY","0",},
{[PS.:     141: 3]  | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     142: 4]  | | | {"R","0",},
:[.s.:     143: 4]  | | | {"G","0",},
:[.s.:     144: 4]  | | | {"B","0",},
:[.s.:     145: 4]  | | | {"A","1",},
:[   :     146: 3]  | | <<< }
{[PS.:     147: 3]  | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     148: 4]  | | | {"R","1",},
:[.s.:     149: 4]  | | | {"G","1",},
:[.s.:     150: 4]  | | | {"B","1",},
:[.s.:     151: 4]  | | | {"A","1",},
:[   :     152: 3]  | | <<< }
{[PS.:     153: 3]  | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     154: 4]  | | | {"R","1",},
:[.s.:     155: 4]  | | | {"G","1",},
:[.s.:     156: 4]  | | | {"B","1",},
:[.s.:     157: 4]  | | | {"A","1",},
:[   :     158: 3]  | | <<< }
:[.S.:     159: 3]  | | {"Shape","Rectangle",},
:[.s.:     160: 3]  | | {"SolidColour","False",},
:[.s.:     161: 3]  | | {"HasDropShadow","False",},
:[.s.:     162: 3]  | | {"HasOuterGradient","False",},
:[.s.:     163: 3]  | | {"HasInnerGradient","False",},
:[.S.:     164: 3]  | | {"Gradient","None",},
:[.s.:     165: 3]  | | {"GradientStartOffset","0",},
:[.s.:     166: 3]  | | {"GradientEndOffset","0",},
:[.s.:     167: 3]  | | {"GradientOffsetPercent","False",},
{[PS.:     168: 3]  | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     169: 4]  | | | {"R","0",},
:[.s.:     170: 4]  | | | {"G","0",},
:[.s.:     171: 4]  | | | {"B","0",},
:[.s.:     172: 4]  | | | {"A","1",},
:[   :     173: 3]  | | <<< }
:[.s.:     174: 3]  | | {"CornerRadius","0",},
:[.s.:     175: 3]  | | {"StrokeSize","0",},
:[.s.:     176: 3]  | | {"Image","0",},
:[.s.:     177: 3]  | | {"Icon","0",},
:[.s.:     178: 3]  | | {"StrokeGradient","False",},
:[.s.:     179: 3]  | | {"StrokeGradientOffset","0",},
:[.s.:     180: 3]  | | {"StrokeGradientFeather","0",},
{[PS.:     181: 3]  | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     182: 4]  | | | {"R","1",},
:[.s.:     183: 4]  | | | {"G","1",},
:[.s.:     184: 4]  | | | {"B","1",},
:[.s.:     185: 4]  | | | {"A","1",},
:[   :     186: 3]  | | <<< }
:[   :     187: 2]  | <<< }
:[.s.:     188: 2]  | {"InheritStyleFromParentLayer","False",},
:[.s.:     189: 2]  | {"HighlightTime","0.1",},
:[.s.:     190: 2]  | {"HighlightScale","1",},
:[.s.:     191: 2]  | {"GlobalFade","1",},
:[.SU:     192: 2]  | {"Animate","None",},
:[.su:     193: 2]  | {"AnimTime","0.5",},
:[.s.:     194: 2]  | {"AnimSplit","0.4",},
{[PS.:     195: 2]  | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:     196: 3]  | | {"Curve","Linear",},
:[   :     197: 2]  | <<< }
{[PS.:     198: 2]  | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:     199: 3]  | | {"Curve","Linear",},
:[   :     200: 2]  | <<< }
{[PS.:     201: 2]  | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:     202: 3]  | | {"x","1",},
:[.s.:     203: 3]  | | {"y","1",},
:[   :     204: 2]  | <<< }
{[PS.:     205: 2]  | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:     206: 3]  | | {"x","1",},
:[.s.:     207: 3]  | | {"y","1",},
:[   :     208: 2]  | <<< }
:[   :     209: 1]  <<< }
{[P..:     211: 1]  "Children",
{[P..:     212: 2]  | "GcNGuiLayerData.xml",
{[PS.:     213: 3]  | | "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.SU:     214: 4]  | | | {"ID","BAR1",},
:[.s.:     216: 4]  | | | {"IsHidden","False",},
{[PS.:     217: 4]  | | | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.s.:     218: 5]  | | | | {"PositionX","0",},
:[.s.:     219: 5]  | | | | {"PositionY","0",},
:[.s.:     220: 5]  | | | | {"Width","100",},
:[.s.:     221: 5]  | | | | {"WidthPercentage","True",},
:[.s.:     222: 5]  | | | | {"Height","132",},
:[.s.:     223: 5]  | | | | {"HeightPercentage","False",},
:[.s.:     224: 5]  | | | | {"ConstrainProportions","False",},
:[.s.:     225: 5]  | | | | {"ConstrainAspect","1",},
:[.s.:     226: 5]  | | | | {"ForceAspect","False",},
:[.s.:     227: 5]  | | | | {"Anchor","True",},
:[.s.:     228: 5]  | | | | {"AnchorPercent","False",},
:[.s.:     229: 5]  | | | | {"SameLine","False",},
{[PS.:     230: 5]  | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:     231: 6]  | | | | | {"Vertical","Top",},
:[.S.:     232: 6]  | | | | | {"Horizontal","Left",},
:[   :     233: 5]  | | | | <<< }
:[.s.:     234: 5]  | | | | {"SlowCursorOnHover","False",},
:[.s.:     235: 5]  | | | | {"MaxWidth","0",},
:[   :     238: 4]  | | | <<< }
:[   :     239: 3]  | | <<< }
{[PS.:     240: 3]  | | "Style", / {"Style","TkNGuiGraphicStyle.xml",},
{[PS.:     241: 4]  | | | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:     242: 5]  | | | | {"PaddingX","0",},
:[.s.:     243: 5]  | | | | {"PaddingY","0",},
:[.s.:     244: 5]  | | | | {"MarginX","0",},
:[.s.:     245: 5]  | | | | {"MarginY","0",},
{[PS.:     246: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     247: 6]  | | | | | {"R","0",},
:[.s.:     248: 6]  | | | | | {"G","0",},
:[.s.:     249: 6]  | | | | | {"B","0",},
:[.s.:     250: 6]  | | | | | {"A","1",},
:[   :     251: 5]  | | | | <<< }
{[PS.:     252: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     253: 6]  | | | | | {"R","1",},
:[.s.:     254: 6]  | | | | | {"G","1",},
:[.s.:     255: 6]  | | | | | {"B","1",},
:[.s.:     256: 6]  | | | | | {"A","1",},
:[   :     257: 5]  | | | | <<< }
{[PS.:     258: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     259: 6]  | | | | | {"R","1",},
:[.s.:     260: 6]  | | | | | {"G","1",},
:[.s.:     261: 6]  | | | | | {"B","1",},
:[.s.:     262: 6]  | | | | | {"A","1",},
:[   :     263: 5]  | | | | <<< }
:[.S.:     264: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     265: 5]  | | | | {"SolidColour","True",},
:[.s.:     266: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     267: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     268: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     269: 5]  | | | | {"Gradient","None",},
:[.s.:     270: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     271: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     272: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     273: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     274: 6]  | | | | | {"R","0",},
:[.s.:     275: 6]  | | | | | {"G","0",},
:[.s.:     276: 6]  | | | | | {"B","0",},
:[.s.:     277: 6]  | | | | | {"A","1",},
:[   :     278: 5]  | | | | <<< }
:[.s.:     279: 5]  | | | | {"CornerRadius","0",},
:[.s.:     280: 5]  | | | | {"StrokeSize","0",},
:[.s.:     281: 5]  | | | | {"Image","0",},
:[.s.:     282: 5]  | | | | {"Icon","0",},
:[.s.:     283: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     284: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     285: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     286: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     287: 6]  | | | | | {"R","1",},
:[.s.:     288: 6]  | | | | | {"G","1",},
:[.s.:     289: 6]  | | | | | {"B","1",},
:[.s.:     290: 6]  | | | | | {"A","1",},
:[   :     291: 5]  | | | | <<< }
:[   :     292: 4]  | | | <<< }
{[PS.:     293: 4]  | | | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:     294: 5]  | | | | {"PaddingX","0",},
:[.s.:     295: 5]  | | | | {"PaddingY","0",},
:[.s.:     296: 5]  | | | | {"MarginX","0",},
:[.s.:     297: 5]  | | | | {"MarginY","0",},
{[PS.:     298: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     299: 6]  | | | | | {"R","0",},
:[.s.:     300: 6]  | | | | | {"G","0",},
:[.s.:     301: 6]  | | | | | {"B","0",},
:[.s.:     302: 6]  | | | | | {"A","1",},
:[   :     303: 5]  | | | | <<< }
{[PS.:     304: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     305: 6]  | | | | | {"R","1",},
:[.s.:     306: 6]  | | | | | {"G","1",},
:[.s.:     307: 6]  | | | | | {"B","1",},
:[.s.:     308: 6]  | | | | | {"A","1",},
:[   :     309: 5]  | | | | <<< }
{[PS.:     310: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     311: 6]  | | | | | {"R","1",},
:[.s.:     312: 6]  | | | | | {"G","1",},
:[.s.:     313: 6]  | | | | | {"B","1",},
:[.s.:     314: 6]  | | | | | {"A","1",},
:[   :     315: 5]  | | | | <<< }
:[.S.:     316: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     317: 5]  | | | | {"SolidColour","True",},
:[.s.:     318: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     319: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     320: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     321: 5]  | | | | {"Gradient","None",},
:[.s.:     322: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     323: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     324: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     325: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     326: 6]  | | | | | {"R","0",},
:[.s.:     327: 6]  | | | | | {"G","0",},
:[.s.:     328: 6]  | | | | | {"B","0",},
:[.s.:     329: 6]  | | | | | {"A","1",},
:[   :     330: 5]  | | | | <<< }
:[.s.:     331: 5]  | | | | {"CornerRadius","0",},
:[.s.:     332: 5]  | | | | {"StrokeSize","0",},
:[.s.:     333: 5]  | | | | {"Image","0",},
:[.s.:     334: 5]  | | | | {"Icon","0",},
:[.s.:     335: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     336: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     337: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     338: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     339: 6]  | | | | | {"R","1",},
:[.s.:     340: 6]  | | | | | {"G","1",},
:[.s.:     341: 6]  | | | | | {"B","1",},
:[.s.:     342: 6]  | | | | | {"A","1",},
:[   :     343: 5]  | | | | <<< }
:[   :     344: 4]  | | | <<< }
{[PS.:     345: 4]  | | | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:     346: 5]  | | | | {"PaddingX","0",},
:[.s.:     347: 5]  | | | | {"PaddingY","0",},
:[.s.:     348: 5]  | | | | {"MarginX","0",},
:[.s.:     349: 5]  | | | | {"MarginY","0",},
{[PS.:     350: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     351: 6]  | | | | | {"R","0",},
:[.s.:     352: 6]  | | | | | {"G","0",},
:[.s.:     353: 6]  | | | | | {"B","0",},
:[.s.:     354: 6]  | | | | | {"A","1",},
:[   :     355: 5]  | | | | <<< }
{[PS.:     356: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     357: 6]  | | | | | {"R","1",},
:[.s.:     358: 6]  | | | | | {"G","1",},
:[.s.:     359: 6]  | | | | | {"B","1",},
:[.s.:     360: 6]  | | | | | {"A","1",},
:[   :     361: 5]  | | | | <<< }
{[PS.:     362: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     363: 6]  | | | | | {"R","1",},
:[.s.:     364: 6]  | | | | | {"G","1",},
:[.s.:     365: 6]  | | | | | {"B","1",},
:[.s.:     366: 6]  | | | | | {"A","1",},
:[   :     367: 5]  | | | | <<< }
:[.S.:     368: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     369: 5]  | | | | {"SolidColour","True",},
:[.s.:     370: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     371: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     372: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     373: 5]  | | | | {"Gradient","None",},
:[.s.:     374: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     375: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     376: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     377: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     378: 6]  | | | | | {"R","0",},
:[.s.:     379: 6]  | | | | | {"G","0",},
:[.s.:     380: 6]  | | | | | {"B","0",},
:[.s.:     381: 6]  | | | | | {"A","1",},
:[   :     382: 5]  | | | | <<< }
:[.s.:     383: 5]  | | | | {"CornerRadius","0",},
:[.s.:     384: 5]  | | | | {"StrokeSize","0",},
:[.s.:     385: 5]  | | | | {"Image","0",},
:[.s.:     386: 5]  | | | | {"Icon","0",},
:[.s.:     387: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     388: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     389: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     390: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     391: 6]  | | | | | {"R","1",},
:[.s.:     392: 6]  | | | | | {"G","1",},
:[.s.:     393: 6]  | | | | | {"B","1",},
:[.s.:     394: 6]  | | | | | {"A","1",},
:[   :     395: 5]  | | | | <<< }
:[   :     396: 4]  | | | <<< }
:[.s.:     397: 4]  | | | {"InheritStyleFromParentLayer","False",},
:[.s.:     398: 4]  | | | {"HighlightTime","0.1",},
:[.s.:     399: 4]  | | | {"HighlightScale","1",},
:[.s.:     400: 4]  | | | {"GlobalFade","1",},
:[.S.:     401: 4]  | | | {"Animate","CustomWipe",},
:[.s.:     402: 4]  | | | {"AnimTime","0.8",},
:[.s.:     403: 4]  | | | {"AnimSplit","0.4",},
{[PS.:     404: 4]  | | | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:     405: 5]  | | | | {"Curve","FastInSlowOut",},
:[   :     406: 4]  | | | <<< }
{[PS.:     407: 4]  | | | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:     408: 5]  | | | | {"Curve","FastInSlowOut",},
:[   :     409: 4]  | | | <<< }
{[PS.:     410: 4]  | | | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:     411: 5]  | | | | {"x","0",},
:[.s.:     412: 5]  | | | | {"y","0",},
:[   :     413: 4]  | | | <<< }
{[PS.:     414: 4]  | | | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:     415: 5]  | | | | {"x","0",},
:[.s.:     416: 5]  | | | | {"y","1",},
:[   :     417: 4]  | | | <<< }
:[   :     418: 3]  | | <<< }
:[.S.:     422: 3]  | | {"AltMode","None",},
:[   :     423: 2]  | <<< }
{[P..:     424: 2]  | "GcNGuiLayerData.xml",
{[PS.:     425: 3]  | | "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.SU:     426: 4]  | | | {"ID","BAR2",},
:[.s.:     428: 4]  | | | {"IsHidden","False",},
{[PS.:     429: 4]  | | | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.s.:     430: 5]  | | | | {"PositionX","0",},
:[.su:     431: 5]  | | | | {"PositionY","100",},
:[.s.:     432: 5]  | | | | {"Width","100",},
:[.s.:     433: 5]  | | | | {"WidthPercentage","True",},
:[.s.:     434: 5]  | | | | {"Height","132",},
:[.s.:     435: 5]  | | | | {"HeightPercentage","False",},
:[.s.:     436: 5]  | | | | {"ConstrainProportions","False",},
:[.s.:     437: 5]  | | | | {"ConstrainAspect","1",},
:[.s.:     438: 5]  | | | | {"ForceAspect","False",},
:[.s.:     439: 5]  | | | | {"Anchor","True",},
:[.su:     440: 5]  | | | | {"AnchorPercent","True",},
:[.s.:     441: 5]  | | | | {"SameLine","False",},
{[PS.:     442: 5]  | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.SU:     443: 6]  | | | | | {"Vertical","Bottom",},
:[.S.:     444: 6]  | | | | | {"Horizontal","Left",},
:[   :     445: 5]  | | | | <<< }
:[.s.:     446: 5]  | | | | {"SlowCursorOnHover","False",},
:[.s.:     447: 5]  | | | | {"MaxWidth","0",},
:[   :     450: 4]  | | | <<< }
:[   :     451: 3]  | | <<< }
{[PS.:     452: 3]  | | "Style", / {"Style","TkNGuiGraphicStyle.xml",},
{[PS.:     453: 4]  | | | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:     454: 5]  | | | | {"PaddingX","0",},
:[.s.:     455: 5]  | | | | {"PaddingY","0",},
:[.s.:     456: 5]  | | | | {"MarginX","0",},
:[.s.:     457: 5]  | | | | {"MarginY","0",},
{[PS.:     458: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     459: 6]  | | | | | {"R","0",},
:[.s.:     460: 6]  | | | | | {"G","0",},
:[.s.:     461: 6]  | | | | | {"B","0",},
:[.s.:     462: 6]  | | | | | {"A","1",},
:[   :     463: 5]  | | | | <<< }
{[PS.:     464: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     465: 6]  | | | | | {"R","1",},
:[.s.:     466: 6]  | | | | | {"G","1",},
:[.s.:     467: 6]  | | | | | {"B","1",},
:[.s.:     468: 6]  | | | | | {"A","1",},
:[   :     469: 5]  | | | | <<< }
{[PS.:     470: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     471: 6]  | | | | | {"R","1",},
:[.s.:     472: 6]  | | | | | {"G","1",},
:[.s.:     473: 6]  | | | | | {"B","1",},
:[.s.:     474: 6]  | | | | | {"A","1",},
:[   :     475: 5]  | | | | <<< }
:[.S.:     476: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     477: 5]  | | | | {"SolidColour","True",},
:[.s.:     478: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     479: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     480: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     481: 5]  | | | | {"Gradient","None",},
:[.s.:     482: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     483: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     484: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     485: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     486: 6]  | | | | | {"R","0",},
:[.s.:     487: 6]  | | | | | {"G","0",},
:[.s.:     488: 6]  | | | | | {"B","0",},
:[.s.:     489: 6]  | | | | | {"A","1",},
:[   :     490: 5]  | | | | <<< }
:[.s.:     491: 5]  | | | | {"CornerRadius","0",},
:[.s.:     492: 5]  | | | | {"StrokeSize","0",},
:[.s.:     493: 5]  | | | | {"Image","0",},
:[.s.:     494: 5]  | | | | {"Icon","0",},
:[.s.:     495: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     496: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     497: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     498: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     499: 6]  | | | | | {"R","1",},
:[.s.:     500: 6]  | | | | | {"G","1",},
:[.s.:     501: 6]  | | | | | {"B","1",},
:[.s.:     502: 6]  | | | | | {"A","1",},
:[   :     503: 5]  | | | | <<< }
:[   :     504: 4]  | | | <<< }
{[PS.:     505: 4]  | | | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:     506: 5]  | | | | {"PaddingX","0",},
:[.s.:     507: 5]  | | | | {"PaddingY","0",},
:[.s.:     508: 5]  | | | | {"MarginX","0",},
:[.s.:     509: 5]  | | | | {"MarginY","0",},
{[PS.:     510: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     511: 6]  | | | | | {"R","0",},
:[.s.:     512: 6]  | | | | | {"G","0",},
:[.s.:     513: 6]  | | | | | {"B","0",},
:[.s.:     514: 6]  | | | | | {"A","1",},
:[   :     515: 5]  | | | | <<< }
{[PS.:     516: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     517: 6]  | | | | | {"R","1",},
:[.s.:     518: 6]  | | | | | {"G","1",},
:[.s.:     519: 6]  | | | | | {"B","1",},
:[.s.:     520: 6]  | | | | | {"A","1",},
:[   :     521: 5]  | | | | <<< }
{[PS.:     522: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     523: 6]  | | | | | {"R","1",},
:[.s.:     524: 6]  | | | | | {"G","1",},
:[.s.:     525: 6]  | | | | | {"B","1",},
:[.s.:     526: 6]  | | | | | {"A","1",},
:[   :     527: 5]  | | | | <<< }
:[.S.:     528: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     529: 5]  | | | | {"SolidColour","True",},
:[.s.:     530: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     531: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     532: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     533: 5]  | | | | {"Gradient","None",},
:[.s.:     534: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     535: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     536: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     537: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     538: 6]  | | | | | {"R","0",},
:[.s.:     539: 6]  | | | | | {"G","0",},
:[.s.:     540: 6]  | | | | | {"B","0",},
:[.s.:     541: 6]  | | | | | {"A","1",},
:[   :     542: 5]  | | | | <<< }
:[.s.:     543: 5]  | | | | {"CornerRadius","0",},
:[.s.:     544: 5]  | | | | {"StrokeSize","0",},
:[.s.:     545: 5]  | | | | {"Image","0",},
:[.s.:     546: 5]  | | | | {"Icon","0",},
:[.s.:     547: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     548: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     549: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     550: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     551: 6]  | | | | | {"R","1",},
:[.s.:     552: 6]  | | | | | {"G","1",},
:[.s.:     553: 6]  | | | | | {"B","1",},
:[.s.:     554: 6]  | | | | | {"A","1",},
:[   :     555: 5]  | | | | <<< }
:[   :     556: 4]  | | | <<< }
{[PS.:     557: 4]  | | | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:     558: 5]  | | | | {"PaddingX","0",},
:[.s.:     559: 5]  | | | | {"PaddingY","0",},
:[.s.:     560: 5]  | | | | {"MarginX","0",},
:[.s.:     561: 5]  | | | | {"MarginY","0",},
{[PS.:     562: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     563: 6]  | | | | | {"R","0",},
:[.s.:     564: 6]  | | | | | {"G","0",},
:[.s.:     565: 6]  | | | | | {"B","0",},
:[.s.:     566: 6]  | | | | | {"A","1",},
:[   :     567: 5]  | | | | <<< }
{[PS.:     568: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     569: 6]  | | | | | {"R","1",},
:[.s.:     570: 6]  | | | | | {"G","1",},
:[.s.:     571: 6]  | | | | | {"B","1",},
:[.s.:     572: 6]  | | | | | {"A","1",},
:[   :     573: 5]  | | | | <<< }
{[PS.:     574: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     575: 6]  | | | | | {"R","1",},
:[.s.:     576: 6]  | | | | | {"G","1",},
:[.s.:     577: 6]  | | | | | {"B","1",},
:[.s.:     578: 6]  | | | | | {"A","1",},
:[   :     579: 5]  | | | | <<< }
:[.S.:     580: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     581: 5]  | | | | {"SolidColour","True",},
:[.s.:     582: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     583: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     584: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     585: 5]  | | | | {"Gradient","None",},
:[.s.:     586: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     587: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     588: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     589: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     590: 6]  | | | | | {"R","0",},
:[.s.:     591: 6]  | | | | | {"G","0",},
:[.s.:     592: 6]  | | | | | {"B","0",},
:[.s.:     593: 6]  | | | | | {"A","1",},
:[   :     594: 5]  | | | | <<< }
:[.s.:     595: 5]  | | | | {"CornerRadius","0",},
:[.s.:     596: 5]  | | | | {"StrokeSize","0",},
:[.s.:     597: 5]  | | | | {"Image","0",},
:[.s.:     598: 5]  | | | | {"Icon","0",},
:[.s.:     599: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     600: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     601: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     602: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     603: 6]  | | | | | {"R","1",},
:[.s.:     604: 6]  | | | | | {"G","1",},
:[.s.:     605: 6]  | | | | | {"B","1",},
:[.s.:     606: 6]  | | | | | {"A","1",},
:[   :     607: 5]  | | | | <<< }
:[   :     608: 4]  | | | <<< }
:[.s.:     609: 4]  | | | {"InheritStyleFromParentLayer","False",},
:[.s.:     610: 4]  | | | {"HighlightTime","0.1",},
:[.s.:     611: 4]  | | | {"HighlightScale","1",},
:[.s.:     612: 4]  | | | {"GlobalFade","1",},
:[.S.:     613: 4]  | | | {"Animate","CustomWipe",},
:[.s.:     614: 4]  | | | {"AnimTime","0.8",},
:[.s.:     615: 4]  | | | {"AnimSplit","0.4",},
{[PS.:     616: 4]  | | | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:     617: 5]  | | | | {"Curve","FastInSlowOut",},
:[   :     618: 4]  | | | <<< }
{[PS.:     619: 4]  | | | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:     620: 5]  | | | | {"Curve","FastInSlowOut",},
:[   :     621: 4]  | | | <<< }
{[PS.:     622: 4]  | | | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:     623: 5]  | | | | {"x","0",},
:[.s.:     624: 5]  | | | | {"y","1",},
:[   :     625: 4]  | | | <<< }
{[PS.:     626: 4]  | | | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:     627: 5]  | | | | {"x","0",},
:[.s.:     628: 5]  | | | | {"y","0",},
:[   :     629: 4]  | | | <<< }
:[   :     630: 3]  | | <<< }
:[.S.:     634: 3]  | | {"AltMode","None",},
:[   :     635: 2]  | <<< }
:[   :     636: 1]  <<< }
:[.SU:     637: 1]  {"DataFilename","UI/COMPONENTS/INTERACTION/CINEMATICBARS.MBIN",},
:[.S.:     638: 1]  {"AltMode","None",},
:[   :     639: 0]/Data } --Do not use, NOT a KEYWORD
 TYPE:FILELINE:LEVEL     KEYWORDS
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
>>> MapFileTree: UI\COMPONENTS\INTERACTION\CINEMATICBARS.EXML (NMSARC.515F1D3.pak) "2022/03/16-18:34:38"
