>>> MapFileTree: UI\HUD\HUDBARS.EXML (NMSARC.515F1D3.pak) "2022/03/16-18:34:38"
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 TYPE:FILELINE:LEVEL     KEYWORDS
{[   :       3: 0]GcNGuiLayerData --Do not use, NOT a KEYWORD
{[PS.:       4: 1]  "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.s.:       7: 2]  | {"IsHidden","False",},
{[PS.:       8: 2]  | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.su:       9: 3]  | | {"PositionX","-10",},
:[.su:      10: 3]  | | {"PositionY","-10",},
:[.su:      11: 3]  | | {"Width","101.99999",},
:[.s.:      12: 3]  | | {"WidthPercentage","True",},
:[.su:      13: 3]  | | {"Height","102",},
:[.s.:      14: 3]  | | {"HeightPercentage","True",},
:[.s.:      15: 3]  | | {"ConstrainProportions","False",},
:[.s.:      16: 3]  | | {"ConstrainAspect","1",},
:[.s.:      17: 3]  | | {"ForceAspect","False",},
:[.s.:      18: 3]  | | {"Anchor","True",},
:[.s.:      19: 3]  | | {"AnchorPercent","False",},
:[.s.:      20: 3]  | | {"SameLine","False",},
{[PS.:      21: 3]  | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:      22: 4]  | | | {"Vertical","Top",},
:[.S.:      23: 4]  | | | {"Horizontal","Left",},
:[   :      24: 3]  | | <<< }
:[.s.:      25: 3]  | | {"SlowCursorOnHover","False",},
:[.s.:      26: 3]  | | {"MaxWidth","0",},
:[   :      29: 2]  | <<< }
:[   :      30: 1]  <<< }
{[PS.:      31: 1]  "Style", / {"Style","TkNGuiGraphicStyle.xml",},
{[PS.:      32: 2]  | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:      33: 3]  | | {"PaddingX","0",},
:[.s.:      34: 3]  | | {"PaddingY","0",},
:[.s.:      35: 3]  | | {"MarginX","0",},
:[.s.:      36: 3]  | | {"MarginY","0",},
{[PS.:      37: 3]  | | "Colour", / {"Colour","Colour.xml",},
:[.s.:      38: 4]  | | | {"R","0",},
:[.s.:      39: 4]  | | | {"G","0",},
:[.s.:      40: 4]  | | | {"B","0",},
:[.s.:      41: 4]  | | | {"A","1",},
:[   :      42: 3]  | | <<< }
{[PS.:      43: 3]  | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:      44: 4]  | | | {"R","1",},
:[.s.:      45: 4]  | | | {"G","1",},
:[.s.:      46: 4]  | | | {"B","1",},
:[.s.:      47: 4]  | | | {"A","1",},
:[   :      48: 3]  | | <<< }
{[PS.:      49: 3]  | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:      50: 4]  | | | {"R","1",},
:[.s.:      51: 4]  | | | {"G","1",},
:[.s.:      52: 4]  | | | {"B","1",},
:[.s.:      53: 4]  | | | {"A","1",},
:[   :      54: 3]  | | <<< }
:[.S.:      55: 3]  | | {"Shape","Rectangle",},
:[.s.:      56: 3]  | | {"SolidColour","False",},
:[.s.:      57: 3]  | | {"HasDropShadow","False",},
:[.s.:      58: 3]  | | {"HasOuterGradient","False",},
:[.s.:      59: 3]  | | {"HasInnerGradient","False",},
:[.S.:      60: 3]  | | {"Gradient","None",},
:[.s.:      61: 3]  | | {"GradientStartOffset","0",},
:[.s.:      62: 3]  | | {"GradientEndOffset","0",},
:[.s.:      63: 3]  | | {"GradientOffsetPercent","False",},
{[PS.:      64: 3]  | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:      65: 4]  | | | {"R","0",},
:[.s.:      66: 4]  | | | {"G","0",},
:[.s.:      67: 4]  | | | {"B","0",},
:[.s.:      68: 4]  | | | {"A","1",},
:[   :      69: 3]  | | <<< }
:[.s.:      70: 3]  | | {"CornerRadius","0",},
:[.s.:      71: 3]  | | {"StrokeSize","0",},
:[.s.:      72: 3]  | | {"Image","0",},
:[.s.:      73: 3]  | | {"Icon","0",},
:[.s.:      74: 3]  | | {"StrokeGradient","False",},
:[.s.:      75: 3]  | | {"StrokeGradientOffset","0",},
:[.s.:      76: 3]  | | {"StrokeGradientFeather","0",},
{[PS.:      77: 3]  | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:      78: 4]  | | | {"R","1",},
:[.s.:      79: 4]  | | | {"G","1",},
:[.s.:      80: 4]  | | | {"B","1",},
:[.s.:      81: 4]  | | | {"A","1",},
:[   :      82: 3]  | | <<< }
:[   :      83: 2]  | <<< }
{[PS.:      84: 2]  | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:      85: 3]  | | {"PaddingX","0",},
:[.s.:      86: 3]  | | {"PaddingY","0",},
:[.s.:      87: 3]  | | {"MarginX","0",},
:[.s.:      88: 3]  | | {"MarginY","0",},
{[PS.:      89: 3]  | | "Colour", / {"Colour","Colour.xml",},
:[.s.:      90: 4]  | | | {"R","0",},
:[.s.:      91: 4]  | | | {"G","0",},
:[.s.:      92: 4]  | | | {"B","0",},
:[.s.:      93: 4]  | | | {"A","1",},
:[   :      94: 3]  | | <<< }
{[PS.:      95: 3]  | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:      96: 4]  | | | {"R","1",},
:[.s.:      97: 4]  | | | {"G","1",},
:[.s.:      98: 4]  | | | {"B","1",},
:[.s.:      99: 4]  | | | {"A","1",},
:[   :     100: 3]  | | <<< }
{[PS.:     101: 3]  | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     102: 4]  | | | {"R","1",},
:[.s.:     103: 4]  | | | {"G","1",},
:[.s.:     104: 4]  | | | {"B","1",},
:[.s.:     105: 4]  | | | {"A","1",},
:[   :     106: 3]  | | <<< }
:[.S.:     107: 3]  | | {"Shape","Rectangle",},
:[.s.:     108: 3]  | | {"SolidColour","False",},
:[.s.:     109: 3]  | | {"HasDropShadow","False",},
:[.s.:     110: 3]  | | {"HasOuterGradient","False",},
:[.s.:     111: 3]  | | {"HasInnerGradient","False",},
:[.S.:     112: 3]  | | {"Gradient","None",},
:[.s.:     113: 3]  | | {"GradientStartOffset","0",},
:[.s.:     114: 3]  | | {"GradientEndOffset","0",},
:[.s.:     115: 3]  | | {"GradientOffsetPercent","False",},
{[PS.:     116: 3]  | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     117: 4]  | | | {"R","0",},
:[.s.:     118: 4]  | | | {"G","0",},
:[.s.:     119: 4]  | | | {"B","0",},
:[.s.:     120: 4]  | | | {"A","1",},
:[   :     121: 3]  | | <<< }
:[.s.:     122: 3]  | | {"CornerRadius","0",},
:[.s.:     123: 3]  | | {"StrokeSize","0",},
:[.s.:     124: 3]  | | {"Image","0",},
:[.s.:     125: 3]  | | {"Icon","0",},
:[.s.:     126: 3]  | | {"StrokeGradient","False",},
:[.s.:     127: 3]  | | {"StrokeGradientOffset","0",},
:[.s.:     128: 3]  | | {"StrokeGradientFeather","0",},
{[PS.:     129: 3]  | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     130: 4]  | | | {"R","1",},
:[.s.:     131: 4]  | | | {"G","1",},
:[.s.:     132: 4]  | | | {"B","1",},
:[.s.:     133: 4]  | | | {"A","1",},
:[   :     134: 3]  | | <<< }
:[   :     135: 2]  | <<< }
{[PS.:     136: 2]  | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:     137: 3]  | | {"PaddingX","0",},
:[.s.:     138: 3]  | | {"PaddingY","0",},
:[.s.:     139: 3]  | | {"MarginX","0",},
:[.s.:     140: 3]  | | {"MarginY","0",},
{[PS.:     141: 3]  | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     142: 4]  | | | {"R","0",},
:[.s.:     143: 4]  | | | {"G","0",},
:[.s.:     144: 4]  | | | {"B","0",},
:[.s.:     145: 4]  | | | {"A","1",},
:[   :     146: 3]  | | <<< }
{[PS.:     147: 3]  | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     148: 4]  | | | {"R","1",},
:[.s.:     149: 4]  | | | {"G","1",},
:[.s.:     150: 4]  | | | {"B","1",},
:[.s.:     151: 4]  | | | {"A","1",},
:[   :     152: 3]  | | <<< }
{[PS.:     153: 3]  | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     154: 4]  | | | {"R","1",},
:[.s.:     155: 4]  | | | {"G","1",},
:[.s.:     156: 4]  | | | {"B","1",},
:[.s.:     157: 4]  | | | {"A","1",},
:[   :     158: 3]  | | <<< }
:[.S.:     159: 3]  | | {"Shape","Rectangle",},
:[.s.:     160: 3]  | | {"SolidColour","False",},
:[.s.:     161: 3]  | | {"HasDropShadow","False",},
:[.s.:     162: 3]  | | {"HasOuterGradient","False",},
:[.s.:     163: 3]  | | {"HasInnerGradient","False",},
:[.S.:     164: 3]  | | {"Gradient","None",},
:[.s.:     165: 3]  | | {"GradientStartOffset","0",},
:[.s.:     166: 3]  | | {"GradientEndOffset","0",},
:[.s.:     167: 3]  | | {"GradientOffsetPercent","False",},
{[PS.:     168: 3]  | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     169: 4]  | | | {"R","0",},
:[.s.:     170: 4]  | | | {"G","0",},
:[.s.:     171: 4]  | | | {"B","0",},
:[.s.:     172: 4]  | | | {"A","1",},
:[   :     173: 3]  | | <<< }
:[.s.:     174: 3]  | | {"CornerRadius","0",},
:[.s.:     175: 3]  | | {"StrokeSize","0",},
:[.s.:     176: 3]  | | {"Image","0",},
:[.s.:     177: 3]  | | {"Icon","0",},
:[.s.:     178: 3]  | | {"StrokeGradient","False",},
:[.s.:     179: 3]  | | {"StrokeGradientOffset","0",},
:[.s.:     180: 3]  | | {"StrokeGradientFeather","0",},
{[PS.:     181: 3]  | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     182: 4]  | | | {"R","1",},
:[.s.:     183: 4]  | | | {"G","1",},
:[.s.:     184: 4]  | | | {"B","1",},
:[.s.:     185: 4]  | | | {"A","1",},
:[   :     186: 3]  | | <<< }
:[   :     187: 2]  | <<< }
:[.s.:     188: 2]  | {"InheritStyleFromParentLayer","False",},
:[.s.:     189: 2]  | {"HighlightTime","0.1",},
:[.s.:     190: 2]  | {"HighlightScale","1",},
:[.s.:     191: 2]  | {"GlobalFade","1",},
:[.S.:     192: 2]  | {"Animate","None",},
:[.s.:     193: 2]  | {"AnimTime","0.5",},
:[.s.:     194: 2]  | {"AnimSplit","0.4",},
{[PS.:     195: 2]  | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:     196: 3]  | | {"Curve","Linear",},
:[   :     197: 2]  | <<< }
{[PS.:     198: 2]  | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:     199: 3]  | | {"Curve","Linear",},
:[   :     200: 2]  | <<< }
{[PS.:     201: 2]  | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:     202: 3]  | | {"x","1",},
:[.s.:     203: 3]  | | {"y","1",},
:[   :     204: 2]  | <<< }
{[PS.:     205: 2]  | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:     206: 3]  | | {"x","1",},
:[.s.:     207: 3]  | | {"y","1",},
:[   :     208: 2]  | <<< }
:[   :     209: 1]  <<< }
{[P..:     211: 1]  "Children",
{[P..:     212: 2]  | "GcNGuiLayerData.xml",
{[PS.:     213: 3]  | | "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.SU:     214: 4]  | | | {"ID","BARS",},
:[.s.:     216: 4]  | | | {"IsHidden","False",},
{[PS.:     217: 4]  | | | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.s.:     218: 5]  | | | | {"PositionX","0",},
:[.s.:     219: 5]  | | | | {"PositionY","0",},
:[.s.:     220: 5]  | | | | {"Width","100",},
:[.s.:     221: 5]  | | | | {"WidthPercentage","True",},
:[.s.:     222: 5]  | | | | {"Height","100",},
:[.s.:     223: 5]  | | | | {"HeightPercentage","True",},
:[.s.:     224: 5]  | | | | {"ConstrainProportions","False",},
:[.s.:     225: 5]  | | | | {"ConstrainAspect","1",},
:[.s.:     226: 5]  | | | | {"ForceAspect","False",},
:[.s.:     227: 5]  | | | | {"Anchor","True",},
:[.s.:     228: 5]  | | | | {"AnchorPercent","False",},
:[.s.:     229: 5]  | | | | {"SameLine","False",},
{[PS.:     230: 5]  | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:     231: 6]  | | | | | {"Vertical","Top",},
:[.S.:     232: 6]  | | | | | {"Horizontal","Left",},
:[   :     233: 5]  | | | | <<< }
:[.s.:     234: 5]  | | | | {"SlowCursorOnHover","False",},
:[.s.:     235: 5]  | | | | {"MaxWidth","0",},
:[   :     238: 4]  | | | <<< }
:[   :     239: 3]  | | <<< }
{[PS.:     240: 3]  | | "Style", / {"Style","TkNGuiGraphicStyle.xml",},
{[PS.:     241: 4]  | | | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:     242: 5]  | | | | {"PaddingX","0",},
:[.s.:     243: 5]  | | | | {"PaddingY","0",},
:[.s.:     244: 5]  | | | | {"MarginX","0",},
:[.s.:     245: 5]  | | | | {"MarginY","0",},
{[PS.:     246: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     247: 6]  | | | | | {"R","0",},
:[.s.:     248: 6]  | | | | | {"G","0",},
:[.s.:     249: 6]  | | | | | {"B","0",},
:[.s.:     250: 6]  | | | | | {"A","1",},
:[   :     251: 5]  | | | | <<< }
{[PS.:     252: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     253: 6]  | | | | | {"R","1",},
:[.s.:     254: 6]  | | | | | {"G","1",},
:[.s.:     255: 6]  | | | | | {"B","1",},
:[.s.:     256: 6]  | | | | | {"A","1",},
:[   :     257: 5]  | | | | <<< }
{[PS.:     258: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     259: 6]  | | | | | {"R","1",},
:[.s.:     260: 6]  | | | | | {"G","1",},
:[.s.:     261: 6]  | | | | | {"B","1",},
:[.s.:     262: 6]  | | | | | {"A","1",},
:[   :     263: 5]  | | | | <<< }
:[.S.:     264: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     265: 5]  | | | | {"SolidColour","False",},
:[.s.:     266: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     267: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     268: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     269: 5]  | | | | {"Gradient","None",},
:[.s.:     270: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     271: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     272: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     273: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     274: 6]  | | | | | {"R","0",},
:[.s.:     275: 6]  | | | | | {"G","0",},
:[.s.:     276: 6]  | | | | | {"B","0",},
:[.s.:     277: 6]  | | | | | {"A","1",},
:[   :     278: 5]  | | | | <<< }
:[.s.:     279: 5]  | | | | {"CornerRadius","0",},
:[.s.:     280: 5]  | | | | {"StrokeSize","0",},
:[.s.:     281: 5]  | | | | {"Image","0",},
:[.s.:     282: 5]  | | | | {"Icon","0",},
:[.s.:     283: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     284: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     285: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     286: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     287: 6]  | | | | | {"R","1",},
:[.s.:     288: 6]  | | | | | {"G","1",},
:[.s.:     289: 6]  | | | | | {"B","1",},
:[.s.:     290: 6]  | | | | | {"A","1",},
:[   :     291: 5]  | | | | <<< }
:[   :     292: 4]  | | | <<< }
{[PS.:     293: 4]  | | | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:     294: 5]  | | | | {"PaddingX","0",},
:[.s.:     295: 5]  | | | | {"PaddingY","0",},
:[.s.:     296: 5]  | | | | {"MarginX","0",},
:[.s.:     297: 5]  | | | | {"MarginY","0",},
{[PS.:     298: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     299: 6]  | | | | | {"R","0",},
:[.s.:     300: 6]  | | | | | {"G","0",},
:[.s.:     301: 6]  | | | | | {"B","0",},
:[.s.:     302: 6]  | | | | | {"A","1",},
:[   :     303: 5]  | | | | <<< }
{[PS.:     304: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     305: 6]  | | | | | {"R","1",},
:[.s.:     306: 6]  | | | | | {"G","1",},
:[.s.:     307: 6]  | | | | | {"B","1",},
:[.s.:     308: 6]  | | | | | {"A","1",},
:[   :     309: 5]  | | | | <<< }
{[PS.:     310: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     311: 6]  | | | | | {"R","1",},
:[.s.:     312: 6]  | | | | | {"G","1",},
:[.s.:     313: 6]  | | | | | {"B","1",},
:[.s.:     314: 6]  | | | | | {"A","1",},
:[   :     315: 5]  | | | | <<< }
:[.S.:     316: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     317: 5]  | | | | {"SolidColour","False",},
:[.s.:     318: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     319: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     320: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     321: 5]  | | | | {"Gradient","None",},
:[.s.:     322: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     323: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     324: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     325: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     326: 6]  | | | | | {"R","0",},
:[.s.:     327: 6]  | | | | | {"G","0",},
:[.s.:     328: 6]  | | | | | {"B","0",},
:[.s.:     329: 6]  | | | | | {"A","1",},
:[   :     330: 5]  | | | | <<< }
:[.s.:     331: 5]  | | | | {"CornerRadius","0",},
:[.s.:     332: 5]  | | | | {"StrokeSize","0",},
:[.s.:     333: 5]  | | | | {"Image","0",},
:[.s.:     334: 5]  | | | | {"Icon","0",},
:[.s.:     335: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     336: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     337: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     338: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     339: 6]  | | | | | {"R","1",},
:[.s.:     340: 6]  | | | | | {"G","1",},
:[.s.:     341: 6]  | | | | | {"B","1",},
:[.s.:     342: 6]  | | | | | {"A","1",},
:[   :     343: 5]  | | | | <<< }
:[   :     344: 4]  | | | <<< }
{[PS.:     345: 4]  | | | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:     346: 5]  | | | | {"PaddingX","0",},
:[.s.:     347: 5]  | | | | {"PaddingY","0",},
:[.s.:     348: 5]  | | | | {"MarginX","0",},
:[.s.:     349: 5]  | | | | {"MarginY","0",},
{[PS.:     350: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     351: 6]  | | | | | {"R","0",},
:[.s.:     352: 6]  | | | | | {"G","0",},
:[.s.:     353: 6]  | | | | | {"B","0",},
:[.s.:     354: 6]  | | | | | {"A","1",},
:[   :     355: 5]  | | | | <<< }
{[PS.:     356: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     357: 6]  | | | | | {"R","1",},
:[.s.:     358: 6]  | | | | | {"G","1",},
:[.s.:     359: 6]  | | | | | {"B","1",},
:[.s.:     360: 6]  | | | | | {"A","1",},
:[   :     361: 5]  | | | | <<< }
{[PS.:     362: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     363: 6]  | | | | | {"R","1",},
:[.s.:     364: 6]  | | | | | {"G","1",},
:[.s.:     365: 6]  | | | | | {"B","1",},
:[.s.:     366: 6]  | | | | | {"A","1",},
:[   :     367: 5]  | | | | <<< }
:[.S.:     368: 5]  | | | | {"Shape","Rectangle",},
:[.s.:     369: 5]  | | | | {"SolidColour","False",},
:[.s.:     370: 5]  | | | | {"HasDropShadow","False",},
:[.s.:     371: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:     372: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:     373: 5]  | | | | {"Gradient","None",},
:[.s.:     374: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:     375: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:     376: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:     377: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     378: 6]  | | | | | {"R","0",},
:[.s.:     379: 6]  | | | | | {"G","0",},
:[.s.:     380: 6]  | | | | | {"B","0",},
:[.s.:     381: 6]  | | | | | {"A","1",},
:[   :     382: 5]  | | | | <<< }
:[.s.:     383: 5]  | | | | {"CornerRadius","0",},
:[.s.:     384: 5]  | | | | {"StrokeSize","0",},
:[.s.:     385: 5]  | | | | {"Image","0",},
:[.s.:     386: 5]  | | | | {"Icon","0",},
:[.s.:     387: 5]  | | | | {"StrokeGradient","False",},
:[.s.:     388: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:     389: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:     390: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     391: 6]  | | | | | {"R","1",},
:[.s.:     392: 6]  | | | | | {"G","1",},
:[.s.:     393: 6]  | | | | | {"B","1",},
:[.s.:     394: 6]  | | | | | {"A","1",},
:[   :     395: 5]  | | | | <<< }
:[   :     396: 4]  | | | <<< }
:[.s.:     397: 4]  | | | {"InheritStyleFromParentLayer","False",},
:[.s.:     398: 4]  | | | {"HighlightTime","0.1",},
:[.s.:     399: 4]  | | | {"HighlightScale","1",},
:[.s.:     400: 4]  | | | {"GlobalFade","1",},
:[.S.:     401: 4]  | | | {"Animate","None",},
:[.su:     402: 4]  | | | {"AnimTime","3",},
:[.s.:     403: 4]  | | | {"AnimSplit","0.4",},
{[PS.:     404: 4]  | | | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:     405: 5]  | | | | {"Curve","Linear",},
:[   :     406: 4]  | | | <<< }
{[PS.:     407: 4]  | | | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:     408: 5]  | | | | {"Curve","Linear",},
:[   :     409: 4]  | | | <<< }
{[PS.:     410: 4]  | | | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:     411: 5]  | | | | {"x","0",},
:[.su:     412: 5]  | | | | {"y","0.5",},
:[   :     413: 4]  | | | <<< }
{[PS.:     414: 4]  | | | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:     415: 5]  | | | | {"x","0",},
:[.s.:     416: 5]  | | | | {"y","0",},
:[   :     417: 4]  | | | <<< }
:[   :     418: 3]  | | <<< }
{[P..:     420: 3]  | | "Children",
{[P..:     421: 4]  | | | "GcNGuiLayerData.xml",
{[PS.:     422: 5]  | | | | "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.SU:     423: 6]  | | | | | {"ID","BAR1",},
:[.s.:     425: 6]  | | | | | {"IsHidden","False",},
{[PS.:     426: 6]  | | | | | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.s.:     427: 7]  | | | | | | {"PositionX","0",},
:[.s.:     428: 7]  | | | | | | {"PositionY","0",},
:[.s.:     429: 7]  | | | | | | {"Width","100",},
:[.s.:     430: 7]  | | | | | | {"WidthPercentage","True",},
:[.s.:     431: 7]  | | | | | | {"Height","100",},
:[.s.:     432: 7]  | | | | | | {"HeightPercentage","False",},
:[.s.:     433: 7]  | | | | | | {"ConstrainProportions","False",},
:[.s.:     434: 7]  | | | | | | {"ConstrainAspect","1",},
:[.s.:     435: 7]  | | | | | | {"ForceAspect","False",},
:[.s.:     436: 7]  | | | | | | {"Anchor","True",},
:[.s.:     437: 7]  | | | | | | {"AnchorPercent","False",},
:[.s.:     438: 7]  | | | | | | {"SameLine","False",},
{[PS.:     439: 7]  | | | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:     440: 8]  | | | | | | | {"Vertical","Top",},
:[.S.:     441: 8]  | | | | | | | {"Horizontal","Left",},
:[   :     442: 7]  | | | | | | <<< }
:[.s.:     443: 7]  | | | | | | {"SlowCursorOnHover","False",},
:[.s.:     444: 7]  | | | | | | {"MaxWidth","0",},
:[   :     447: 6]  | | | | | <<< }
:[   :     448: 5]  | | | | <<< }
{[PS.:     449: 5]  | | | | "Style", / {"Style","TkNGuiGraphicStyle.xml",},
{[PS.:     450: 6]  | | | | | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:     451: 7]  | | | | | | {"PaddingX","0",},
:[.s.:     452: 7]  | | | | | | {"PaddingY","0",},
:[.s.:     453: 7]  | | | | | | {"MarginX","0",},
:[.s.:     454: 7]  | | | | | | {"MarginY","0",},
{[PS.:     455: 7]  | | | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     456: 8]  | | | | | | | {"R","0",},
:[.s.:     457: 8]  | | | | | | | {"G","0",},
:[.s.:     458: 8]  | | | | | | | {"B","0",},
:[.s.:     459: 8]  | | | | | | | {"A","1",},
:[   :     460: 7]  | | | | | | <<< }
{[PS.:     461: 7]  | | | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     462: 8]  | | | | | | | {"R","1",},
:[.s.:     463: 8]  | | | | | | | {"G","1",},
:[.s.:     464: 8]  | | | | | | | {"B","1",},
:[.s.:     465: 8]  | | | | | | | {"A","1",},
:[   :     466: 7]  | | | | | | <<< }
{[PS.:     467: 7]  | | | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     468: 8]  | | | | | | | {"R","1",},
:[.s.:     469: 8]  | | | | | | | {"G","1",},
:[.s.:     470: 8]  | | | | | | | {"B","1",},
:[.s.:     471: 8]  | | | | | | | {"A","1",},
:[   :     472: 7]  | | | | | | <<< }
:[.S.:     473: 7]  | | | | | | {"Shape","Rectangle",},
:[.s.:     474: 7]  | | | | | | {"SolidColour","True",},
:[.s.:     475: 7]  | | | | | | {"HasDropShadow","False",},
:[.s.:     476: 7]  | | | | | | {"HasOuterGradient","False",},
:[.s.:     477: 7]  | | | | | | {"HasInnerGradient","False",},
:[.S.:     478: 7]  | | | | | | {"Gradient","None",},
:[.s.:     479: 7]  | | | | | | {"GradientStartOffset","0",},
:[.s.:     480: 7]  | | | | | | {"GradientEndOffset","0",},
:[.s.:     481: 7]  | | | | | | {"GradientOffsetPercent","False",},
{[PS.:     482: 7]  | | | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     483: 8]  | | | | | | | {"R","0",},
:[.s.:     484: 8]  | | | | | | | {"G","0",},
:[.s.:     485: 8]  | | | | | | | {"B","0",},
:[.s.:     486: 8]  | | | | | | | {"A","1",},
:[   :     487: 7]  | | | | | | <<< }
:[.s.:     488: 7]  | | | | | | {"CornerRadius","0",},
:[.s.:     489: 7]  | | | | | | {"StrokeSize","0",},
:[.s.:     490: 7]  | | | | | | {"Image","0",},
:[.s.:     491: 7]  | | | | | | {"Icon","0",},
:[.s.:     492: 7]  | | | | | | {"StrokeGradient","False",},
:[.s.:     493: 7]  | | | | | | {"StrokeGradientOffset","0",},
:[.s.:     494: 7]  | | | | | | {"StrokeGradientFeather","0",},
{[PS.:     495: 7]  | | | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     496: 8]  | | | | | | | {"R","1",},
:[.s.:     497: 8]  | | | | | | | {"G","1",},
:[.s.:     498: 8]  | | | | | | | {"B","1",},
:[.s.:     499: 8]  | | | | | | | {"A","1",},
:[   :     500: 7]  | | | | | | <<< }
:[   :     501: 6]  | | | | | <<< }
{[PS.:     502: 6]  | | | | | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:     503: 7]  | | | | | | {"PaddingX","0",},
:[.s.:     504: 7]  | | | | | | {"PaddingY","0",},
:[.s.:     505: 7]  | | | | | | {"MarginX","0",},
:[.s.:     506: 7]  | | | | | | {"MarginY","0",},
{[PS.:     507: 7]  | | | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     508: 8]  | | | | | | | {"R","0",},
:[.s.:     509: 8]  | | | | | | | {"G","0",},
:[.s.:     510: 8]  | | | | | | | {"B","0",},
:[.s.:     511: 8]  | | | | | | | {"A","1",},
:[   :     512: 7]  | | | | | | <<< }
{[PS.:     513: 7]  | | | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     514: 8]  | | | | | | | {"R","1",},
:[.s.:     515: 8]  | | | | | | | {"G","1",},
:[.s.:     516: 8]  | | | | | | | {"B","1",},
:[.s.:     517: 8]  | | | | | | | {"A","1",},
:[   :     518: 7]  | | | | | | <<< }
{[PS.:     519: 7]  | | | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     520: 8]  | | | | | | | {"R","1",},
:[.s.:     521: 8]  | | | | | | | {"G","1",},
:[.s.:     522: 8]  | | | | | | | {"B","1",},
:[.s.:     523: 8]  | | | | | | | {"A","1",},
:[   :     524: 7]  | | | | | | <<< }
:[.S.:     525: 7]  | | | | | | {"Shape","Rectangle",},
:[.s.:     526: 7]  | | | | | | {"SolidColour","True",},
:[.s.:     527: 7]  | | | | | | {"HasDropShadow","False",},
:[.s.:     528: 7]  | | | | | | {"HasOuterGradient","False",},
:[.s.:     529: 7]  | | | | | | {"HasInnerGradient","False",},
:[.S.:     530: 7]  | | | | | | {"Gradient","None",},
:[.s.:     531: 7]  | | | | | | {"GradientStartOffset","0",},
:[.s.:     532: 7]  | | | | | | {"GradientEndOffset","0",},
:[.s.:     533: 7]  | | | | | | {"GradientOffsetPercent","False",},
{[PS.:     534: 7]  | | | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     535: 8]  | | | | | | | {"R","0",},
:[.s.:     536: 8]  | | | | | | | {"G","0",},
:[.s.:     537: 8]  | | | | | | | {"B","0",},
:[.s.:     538: 8]  | | | | | | | {"A","1",},
:[   :     539: 7]  | | | | | | <<< }
:[.s.:     540: 7]  | | | | | | {"CornerRadius","0",},
:[.s.:     541: 7]  | | | | | | {"StrokeSize","0",},
:[.s.:     542: 7]  | | | | | | {"Image","0",},
:[.s.:     543: 7]  | | | | | | {"Icon","0",},
:[.s.:     544: 7]  | | | | | | {"StrokeGradient","False",},
:[.s.:     545: 7]  | | | | | | {"StrokeGradientOffset","0",},
:[.s.:     546: 7]  | | | | | | {"StrokeGradientFeather","0",},
{[PS.:     547: 7]  | | | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     548: 8]  | | | | | | | {"R","1",},
:[.s.:     549: 8]  | | | | | | | {"G","1",},
:[.s.:     550: 8]  | | | | | | | {"B","1",},
:[.s.:     551: 8]  | | | | | | | {"A","1",},
:[   :     552: 7]  | | | | | | <<< }
:[   :     553: 6]  | | | | | <<< }
{[PS.:     554: 6]  | | | | | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:     555: 7]  | | | | | | {"PaddingX","0",},
:[.s.:     556: 7]  | | | | | | {"PaddingY","0",},
:[.s.:     557: 7]  | | | | | | {"MarginX","0",},
:[.s.:     558: 7]  | | | | | | {"MarginY","0",},
{[PS.:     559: 7]  | | | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     560: 8]  | | | | | | | {"R","0",},
:[.s.:     561: 8]  | | | | | | | {"G","0",},
:[.s.:     562: 8]  | | | | | | | {"B","0",},
:[.s.:     563: 8]  | | | | | | | {"A","1",},
:[   :     564: 7]  | | | | | | <<< }
{[PS.:     565: 7]  | | | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     566: 8]  | | | | | | | {"R","1",},
:[.s.:     567: 8]  | | | | | | | {"G","1",},
:[.s.:     568: 8]  | | | | | | | {"B","1",},
:[.s.:     569: 8]  | | | | | | | {"A","1",},
:[   :     570: 7]  | | | | | | <<< }
{[PS.:     571: 7]  | | | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     572: 8]  | | | | | | | {"R","1",},
:[.s.:     573: 8]  | | | | | | | {"G","1",},
:[.s.:     574: 8]  | | | | | | | {"B","1",},
:[.s.:     575: 8]  | | | | | | | {"A","1",},
:[   :     576: 7]  | | | | | | <<< }
:[.S.:     577: 7]  | | | | | | {"Shape","Rectangle",},
:[.s.:     578: 7]  | | | | | | {"SolidColour","True",},
:[.s.:     579: 7]  | | | | | | {"HasDropShadow","False",},
:[.s.:     580: 7]  | | | | | | {"HasOuterGradient","False",},
:[.s.:     581: 7]  | | | | | | {"HasInnerGradient","False",},
:[.S.:     582: 7]  | | | | | | {"Gradient","None",},
:[.s.:     583: 7]  | | | | | | {"GradientStartOffset","0",},
:[.s.:     584: 7]  | | | | | | {"GradientEndOffset","0",},
:[.s.:     585: 7]  | | | | | | {"GradientOffsetPercent","False",},
{[PS.:     586: 7]  | | | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     587: 8]  | | | | | | | {"R","0",},
:[.s.:     588: 8]  | | | | | | | {"G","0",},
:[.s.:     589: 8]  | | | | | | | {"B","0",},
:[.s.:     590: 8]  | | | | | | | {"A","1",},
:[   :     591: 7]  | | | | | | <<< }
:[.s.:     592: 7]  | | | | | | {"CornerRadius","0",},
:[.s.:     593: 7]  | | | | | | {"StrokeSize","0",},
:[.s.:     594: 7]  | | | | | | {"Image","0",},
:[.s.:     595: 7]  | | | | | | {"Icon","0",},
:[.s.:     596: 7]  | | | | | | {"StrokeGradient","False",},
:[.s.:     597: 7]  | | | | | | {"StrokeGradientOffset","0",},
:[.s.:     598: 7]  | | | | | | {"StrokeGradientFeather","0",},
{[PS.:     599: 7]  | | | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     600: 8]  | | | | | | | {"R","1",},
:[.s.:     601: 8]  | | | | | | | {"G","1",},
:[.s.:     602: 8]  | | | | | | | {"B","1",},
:[.s.:     603: 8]  | | | | | | | {"A","1",},
:[   :     604: 7]  | | | | | | <<< }
:[   :     605: 6]  | | | | | <<< }
:[.s.:     606: 6]  | | | | | {"InheritStyleFromParentLayer","False",},
:[.s.:     607: 6]  | | | | | {"HighlightTime","0.1",},
:[.s.:     608: 6]  | | | | | {"HighlightScale","1",},
:[.s.:     609: 6]  | | | | | {"GlobalFade","1",},
:[.S.:     610: 6]  | | | | | {"Animate","CustomWipe",},
:[.s.:     611: 6]  | | | | | {"AnimTime","1",},
:[.s.:     612: 6]  | | | | | {"AnimSplit","0.4",},
{[PS.:     613: 6]  | | | | | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:     614: 7]  | | | | | | {"Curve","FastInSlowOut",},
:[   :     615: 6]  | | | | | <<< }
{[PS.:     616: 6]  | | | | | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:     617: 7]  | | | | | | {"Curve","FastInSlowOut",},
:[   :     618: 6]  | | | | | <<< }
{[PS.:     619: 6]  | | | | | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:     620: 7]  | | | | | | {"x","0",},
:[.s.:     621: 7]  | | | | | | {"y","0",},
:[   :     622: 6]  | | | | | <<< }
{[PS.:     623: 6]  | | | | | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:     624: 7]  | | | | | | {"x","0",},
:[.s.:     625: 7]  | | | | | | {"y","1",},
:[   :     626: 6]  | | | | | <<< }
:[   :     627: 5]  | | | | <<< }
:[.S.:     631: 5]  | | | | {"AltMode","None",},
:[   :     632: 4]  | | | <<< }
{[P..:     633: 4]  | | | "GcNGuiLayerData.xml",
{[PS.:     634: 5]  | | | | "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.SU:     635: 6]  | | | | | {"ID","BAR2",},
:[.s.:     637: 6]  | | | | | {"IsHidden","False",},
{[PS.:     638: 6]  | | | | | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.s.:     639: 7]  | | | | | | {"PositionX","0",},
:[.su:     640: 7]  | | | | | | {"PositionY","100",},
:[.s.:     641: 7]  | | | | | | {"Width","100",},
:[.s.:     642: 7]  | | | | | | {"WidthPercentage","True",},
:[.s.:     643: 7]  | | | | | | {"Height","100",},
:[.s.:     644: 7]  | | | | | | {"HeightPercentage","False",},
:[.s.:     645: 7]  | | | | | | {"ConstrainProportions","False",},
:[.s.:     646: 7]  | | | | | | {"ConstrainAspect","1",},
:[.s.:     647: 7]  | | | | | | {"ForceAspect","False",},
:[.s.:     648: 7]  | | | | | | {"Anchor","True",},
:[.s.:     649: 7]  | | | | | | {"AnchorPercent","True",},
:[.s.:     650: 7]  | | | | | | {"SameLine","False",},
{[PS.:     651: 7]  | | | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:     652: 8]  | | | | | | | {"Vertical","Bottom",},
:[.S.:     653: 8]  | | | | | | | {"Horizontal","Left",},
:[   :     654: 7]  | | | | | | <<< }
:[.s.:     655: 7]  | | | | | | {"SlowCursorOnHover","False",},
:[.s.:     656: 7]  | | | | | | {"MaxWidth","0",},
:[   :     659: 6]  | | | | | <<< }
:[   :     660: 5]  | | | | <<< }
{[PS.:     661: 5]  | | | | "Style", / {"Style","TkNGuiGraphicStyle.xml",},
{[PS.:     662: 6]  | | | | | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:     663: 7]  | | | | | | {"PaddingX","0",},
:[.s.:     664: 7]  | | | | | | {"PaddingY","0",},
:[.s.:     665: 7]  | | | | | | {"MarginX","0",},
:[.s.:     666: 7]  | | | | | | {"MarginY","0",},
{[PS.:     667: 7]  | | | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     668: 8]  | | | | | | | {"R","0",},
:[.s.:     669: 8]  | | | | | | | {"G","0",},
:[.s.:     670: 8]  | | | | | | | {"B","0",},
:[.s.:     671: 8]  | | | | | | | {"A","1",},
:[   :     672: 7]  | | | | | | <<< }
{[PS.:     673: 7]  | | | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     674: 8]  | | | | | | | {"R","1",},
:[.s.:     675: 8]  | | | | | | | {"G","1",},
:[.s.:     676: 8]  | | | | | | | {"B","1",},
:[.s.:     677: 8]  | | | | | | | {"A","1",},
:[   :     678: 7]  | | | | | | <<< }
{[PS.:     679: 7]  | | | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     680: 8]  | | | | | | | {"R","1",},
:[.s.:     681: 8]  | | | | | | | {"G","1",},
:[.s.:     682: 8]  | | | | | | | {"B","1",},
:[.s.:     683: 8]  | | | | | | | {"A","1",},
:[   :     684: 7]  | | | | | | <<< }
:[.S.:     685: 7]  | | | | | | {"Shape","Rectangle",},
:[.s.:     686: 7]  | | | | | | {"SolidColour","True",},
:[.s.:     687: 7]  | | | | | | {"HasDropShadow","False",},
:[.s.:     688: 7]  | | | | | | {"HasOuterGradient","False",},
:[.s.:     689: 7]  | | | | | | {"HasInnerGradient","False",},
:[.S.:     690: 7]  | | | | | | {"Gradient","None",},
:[.s.:     691: 7]  | | | | | | {"GradientStartOffset","0",},
:[.s.:     692: 7]  | | | | | | {"GradientEndOffset","0",},
:[.s.:     693: 7]  | | | | | | {"GradientOffsetPercent","False",},
{[PS.:     694: 7]  | | | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     695: 8]  | | | | | | | {"R","0",},
:[.s.:     696: 8]  | | | | | | | {"G","0",},
:[.s.:     697: 8]  | | | | | | | {"B","0",},
:[.s.:     698: 8]  | | | | | | | {"A","1",},
:[   :     699: 7]  | | | | | | <<< }
:[.s.:     700: 7]  | | | | | | {"CornerRadius","0",},
:[.s.:     701: 7]  | | | | | | {"StrokeSize","0",},
:[.s.:     702: 7]  | | | | | | {"Image","0",},
:[.s.:     703: 7]  | | | | | | {"Icon","0",},
:[.s.:     704: 7]  | | | | | | {"StrokeGradient","False",},
:[.s.:     705: 7]  | | | | | | {"StrokeGradientOffset","0",},
:[.s.:     706: 7]  | | | | | | {"StrokeGradientFeather","0",},
{[PS.:     707: 7]  | | | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     708: 8]  | | | | | | | {"R","1",},
:[.s.:     709: 8]  | | | | | | | {"G","1",},
:[.s.:     710: 8]  | | | | | | | {"B","1",},
:[.s.:     711: 8]  | | | | | | | {"A","1",},
:[   :     712: 7]  | | | | | | <<< }
:[   :     713: 6]  | | | | | <<< }
{[PS.:     714: 6]  | | | | | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:     715: 7]  | | | | | | {"PaddingX","0",},
:[.s.:     716: 7]  | | | | | | {"PaddingY","0",},
:[.s.:     717: 7]  | | | | | | {"MarginX","0",},
:[.s.:     718: 7]  | | | | | | {"MarginY","0",},
{[PS.:     719: 7]  | | | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     720: 8]  | | | | | | | {"R","0",},
:[.s.:     721: 8]  | | | | | | | {"G","0",},
:[.s.:     722: 8]  | | | | | | | {"B","0",},
:[.s.:     723: 8]  | | | | | | | {"A","1",},
:[   :     724: 7]  | | | | | | <<< }
{[PS.:     725: 7]  | | | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     726: 8]  | | | | | | | {"R","1",},
:[.s.:     727: 8]  | | | | | | | {"G","1",},
:[.s.:     728: 8]  | | | | | | | {"B","1",},
:[.s.:     729: 8]  | | | | | | | {"A","1",},
:[   :     730: 7]  | | | | | | <<< }
{[PS.:     731: 7]  | | | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     732: 8]  | | | | | | | {"R","1",},
:[.s.:     733: 8]  | | | | | | | {"G","1",},
:[.s.:     734: 8]  | | | | | | | {"B","1",},
:[.s.:     735: 8]  | | | | | | | {"A","1",},
:[   :     736: 7]  | | | | | | <<< }
:[.S.:     737: 7]  | | | | | | {"Shape","Rectangle",},
:[.s.:     738: 7]  | | | | | | {"SolidColour","True",},
:[.s.:     739: 7]  | | | | | | {"HasDropShadow","False",},
:[.s.:     740: 7]  | | | | | | {"HasOuterGradient","False",},
:[.s.:     741: 7]  | | | | | | {"HasInnerGradient","False",},
:[.S.:     742: 7]  | | | | | | {"Gradient","None",},
:[.s.:     743: 7]  | | | | | | {"GradientStartOffset","0",},
:[.s.:     744: 7]  | | | | | | {"GradientEndOffset","0",},
:[.s.:     745: 7]  | | | | | | {"GradientOffsetPercent","False",},
{[PS.:     746: 7]  | | | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     747: 8]  | | | | | | | {"R","0",},
:[.s.:     748: 8]  | | | | | | | {"G","0",},
:[.s.:     749: 8]  | | | | | | | {"B","0",},
:[.s.:     750: 8]  | | | | | | | {"A","1",},
:[   :     751: 7]  | | | | | | <<< }
:[.s.:     752: 7]  | | | | | | {"CornerRadius","0",},
:[.s.:     753: 7]  | | | | | | {"StrokeSize","0",},
:[.s.:     754: 7]  | | | | | | {"Image","0",},
:[.s.:     755: 7]  | | | | | | {"Icon","0",},
:[.s.:     756: 7]  | | | | | | {"StrokeGradient","False",},
:[.s.:     757: 7]  | | | | | | {"StrokeGradientOffset","0",},
:[.s.:     758: 7]  | | | | | | {"StrokeGradientFeather","0",},
{[PS.:     759: 7]  | | | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     760: 8]  | | | | | | | {"R","1",},
:[.s.:     761: 8]  | | | | | | | {"G","1",},
:[.s.:     762: 8]  | | | | | | | {"B","1",},
:[.s.:     763: 8]  | | | | | | | {"A","1",},
:[   :     764: 7]  | | | | | | <<< }
:[   :     765: 6]  | | | | | <<< }
{[PS.:     766: 6]  | | | | | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:     767: 7]  | | | | | | {"PaddingX","0",},
:[.s.:     768: 7]  | | | | | | {"PaddingY","0",},
:[.s.:     769: 7]  | | | | | | {"MarginX","0",},
:[.s.:     770: 7]  | | | | | | {"MarginY","0",},
{[PS.:     771: 7]  | | | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     772: 8]  | | | | | | | {"R","0",},
:[.s.:     773: 8]  | | | | | | | {"G","0",},
:[.s.:     774: 8]  | | | | | | | {"B","0",},
:[.s.:     775: 8]  | | | | | | | {"A","1",},
:[   :     776: 7]  | | | | | | <<< }
{[PS.:     777: 7]  | | | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:     778: 8]  | | | | | | | {"R","1",},
:[.s.:     779: 8]  | | | | | | | {"G","1",},
:[.s.:     780: 8]  | | | | | | | {"B","1",},
:[.s.:     781: 8]  | | | | | | | {"A","1",},
:[   :     782: 7]  | | | | | | <<< }
{[PS.:     783: 7]  | | | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:     784: 8]  | | | | | | | {"R","1",},
:[.s.:     785: 8]  | | | | | | | {"G","1",},
:[.s.:     786: 8]  | | | | | | | {"B","1",},
:[.s.:     787: 8]  | | | | | | | {"A","1",},
:[   :     788: 7]  | | | | | | <<< }
:[.S.:     789: 7]  | | | | | | {"Shape","Rectangle",},
:[.s.:     790: 7]  | | | | | | {"SolidColour","True",},
:[.s.:     791: 7]  | | | | | | {"HasDropShadow","False",},
:[.s.:     792: 7]  | | | | | | {"HasOuterGradient","False",},
:[.s.:     793: 7]  | | | | | | {"HasInnerGradient","False",},
:[.S.:     794: 7]  | | | | | | {"Gradient","None",},
:[.s.:     795: 7]  | | | | | | {"GradientStartOffset","0",},
:[.s.:     796: 7]  | | | | | | {"GradientEndOffset","0",},
:[.s.:     797: 7]  | | | | | | {"GradientOffsetPercent","False",},
{[PS.:     798: 7]  | | | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:     799: 8]  | | | | | | | {"R","0",},
:[.s.:     800: 8]  | | | | | | | {"G","0",},
:[.s.:     801: 8]  | | | | | | | {"B","0",},
:[.s.:     802: 8]  | | | | | | | {"A","1",},
:[   :     803: 7]  | | | | | | <<< }
:[.s.:     804: 7]  | | | | | | {"CornerRadius","0",},
:[.s.:     805: 7]  | | | | | | {"StrokeSize","0",},
:[.s.:     806: 7]  | | | | | | {"Image","0",},
:[.s.:     807: 7]  | | | | | | {"Icon","0",},
:[.s.:     808: 7]  | | | | | | {"StrokeGradient","False",},
:[.s.:     809: 7]  | | | | | | {"StrokeGradientOffset","0",},
:[.s.:     810: 7]  | | | | | | {"StrokeGradientFeather","0",},
{[PS.:     811: 7]  | | | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:     812: 8]  | | | | | | | {"R","1",},
:[.s.:     813: 8]  | | | | | | | {"G","1",},
:[.s.:     814: 8]  | | | | | | | {"B","1",},
:[.s.:     815: 8]  | | | | | | | {"A","1",},
:[   :     816: 7]  | | | | | | <<< }
:[   :     817: 6]  | | | | | <<< }
:[.s.:     818: 6]  | | | | | {"InheritStyleFromParentLayer","False",},
:[.s.:     819: 6]  | | | | | {"HighlightTime","0.1",},
:[.s.:     820: 6]  | | | | | {"HighlightScale","1",},
:[.s.:     821: 6]  | | | | | {"GlobalFade","1",},
:[.S.:     822: 6]  | | | | | {"Animate","CustomWipe",},
:[.s.:     823: 6]  | | | | | {"AnimTime","1",},
:[.s.:     824: 6]  | | | | | {"AnimSplit","0.4",},
{[PS.:     825: 6]  | | | | | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:     826: 7]  | | | | | | {"Curve","FastInSlowOut",},
:[   :     827: 6]  | | | | | <<< }
{[PS.:     828: 6]  | | | | | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:     829: 7]  | | | | | | {"Curve","FastInSlowOut",},
:[   :     830: 6]  | | | | | <<< }
{[PS.:     831: 6]  | | | | | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:     832: 7]  | | | | | | {"x","0",},
:[.s.:     833: 7]  | | | | | | {"y","1",},
:[   :     834: 6]  | | | | | <<< }
{[PS.:     835: 6]  | | | | | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:     836: 7]  | | | | | | {"x","0",},
:[.s.:     837: 7]  | | | | | | {"y","0",},
:[   :     838: 6]  | | | | | <<< }
:[   :     839: 5]  | | | | <<< }
:[.S.:     843: 5]  | | | | {"AltMode","None",},
:[   :     844: 4]  | | | <<< }
:[   :     845: 3]  | | <<< }
:[.S.:     847: 3]  | | {"AltMode","None",},
:[   :     848: 2]  | <<< }
{[P..:     849: 2]  | "GcNGuiTextData.xml",
{[PS.:     850: 3]  | | "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.SU:     851: 4]  | | | {"ID","MSG_SKIP",},
:[.SU:     852: 4]  | | | {"PresetID","DEFAULT",},
:[.s.:     853: 4]  | | | {"IsHidden","True",},
{[PS.:     854: 4]  | | | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.s.:     855: 5]  | | | | {"PositionX","50",},
:[.su:     856: 5]  | | | | {"PositionY","94",},
:[.su:     857: 5]  | | | | {"Width","0",},
:[.su:     858: 5]  | | | | {"WidthPercentage","False",},
:[.su:     859: 5]  | | | | {"Height","0",},
:[.s.:     860: 5]  | | | | {"HeightPercentage","False",},
:[.s.:     861: 5]  | | | | {"ConstrainProportions","False",},
:[.s.:     862: 5]  | | | | {"ConstrainAspect","1",},
:[.s.:     863: 5]  | | | | {"ForceAspect","False",},
:[.s.:     864: 5]  | | | | {"Anchor","True",},
:[.s.:     865: 5]  | | | | {"AnchorPercent","True",},
:[.s.:     866: 5]  | | | | {"SameLine","False",},
{[PS.:     867: 5]  | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:     868: 6]  | | | | | {"Vertical","Bottom",},
:[.S.:     869: 6]  | | | | | {"Horizontal","Center",},
:[   :     870: 5]  | | | | <<< }
:[.s.:     871: 5]  | | | | {"SlowCursorOnHover","False",},
:[.s.:     872: 5]  | | | | {"MaxWidth","0",},
:[   :     875: 4]  | | | <<< }
:[   :     876: 3]  | | <<< }
{[PSU:     877: 3]  | | "Style", / {"Style","TkNGuiTextStyle.xml",},
{[PSU:     878: 4]  | | | "Default", / {"Default","TkNGuiTextStyleData.xml",},
{[PS.:     879: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     880: 6]  | | | | | {"R","1",},
:[.s.:     881: 6]  | | | | | {"G","1",},
:[.s.:     882: 6]  | | | | | {"B","1",},
:[.s.:     883: 6]  | | | | | {"A","1",},
:[   :     884: 5]  | | | | <<< }
:[.s.:     885: 5]  | | | | {"FontHeight","24",},
:[.s.:     886: 5]  | | | | {"FontSpacing","0",},
:[.s.:     887: 5]  | | | | {"IsIndented","False",},
:[.s.:     888: 5]  | | | | {"HasDropShadow","False",},
{[PS.:     889: 5]  | | | | "DropShadowColour", / {"DropShadowColour","Colour.xml",},
:[.s.:     890: 6]  | | | | | {"R","0",},
:[.s.:     891: 6]  | | | | | {"G","0",},
:[.s.:     892: 6]  | | | | | {"B","0",},
:[.s.:     893: 6]  | | | | | {"A","1",},
:[   :     894: 5]  | | | | <<< }
:[.s.:     895: 5]  | | | | {"DropShadowAngle","0",},
:[.s.:     896: 5]  | | | | {"DropShadowOffset","1",},
:[.s.:     897: 5]  | | | | {"HasOutline","False",},
:[.s.:     898: 5]  | | | | {"OutlineSize","1",},
{[PS.:     899: 5]  | | | | "OutlineColour", / {"OutlineColour","Colour.xml",},
:[.s.:     900: 6]  | | | | | {"R","1",},
:[.s.:     901: 6]  | | | | | {"G","1",},
:[.s.:     902: 6]  | | | | | {"B","1",},
:[.s.:     903: 6]  | | | | | {"A","1",},
:[   :     904: 5]  | | | | <<< }
:[.s.:     905: 5]  | | | | {"IsParagraph","False",},
:[.s.:     906: 5]  | | | | {"AllowScroll","False",},
:[.s.:     907: 5]  | | | | {"ForceUpperCase","False",},
:[.s.:     908: 5]  | | | | {"AutoAdjustHeight","False",},
:[.s.:     909: 5]  | | | | {"FontIndex","1",},
{[PS.:     910: 5]  | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:     911: 6]  | | | | | {"Vertical","Bottom",},
:[.S.:     912: 6]  | | | | | {"Horizontal","Center",},
:[   :     913: 5]  | | | | <<< }
:[   :     914: 4]  | | | <<< }
{[PSU:     915: 4]  | | | "Highlight", / {"Highlight","TkNGuiTextStyleData.xml",},
{[PS.:     916: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     917: 6]  | | | | | {"R","1",},
:[.s.:     918: 6]  | | | | | {"G","1",},
:[.s.:     919: 6]  | | | | | {"B","1",},
:[.s.:     920: 6]  | | | | | {"A","1",},
:[   :     921: 5]  | | | | <<< }
:[.s.:     922: 5]  | | | | {"FontHeight","24",},
:[.s.:     923: 5]  | | | | {"FontSpacing","0",},
:[.s.:     924: 5]  | | | | {"IsIndented","False",},
:[.s.:     925: 5]  | | | | {"HasDropShadow","False",},
{[PS.:     926: 5]  | | | | "DropShadowColour", / {"DropShadowColour","Colour.xml",},
:[.s.:     927: 6]  | | | | | {"R","0",},
:[.s.:     928: 6]  | | | | | {"G","0",},
:[.s.:     929: 6]  | | | | | {"B","0",},
:[.s.:     930: 6]  | | | | | {"A","1",},
:[   :     931: 5]  | | | | <<< }
:[.s.:     932: 5]  | | | | {"DropShadowAngle","0",},
:[.s.:     933: 5]  | | | | {"DropShadowOffset","1",},
:[.s.:     934: 5]  | | | | {"HasOutline","False",},
:[.s.:     935: 5]  | | | | {"OutlineSize","1",},
{[PS.:     936: 5]  | | | | "OutlineColour", / {"OutlineColour","Colour.xml",},
:[.s.:     937: 6]  | | | | | {"R","1",},
:[.s.:     938: 6]  | | | | | {"G","1",},
:[.s.:     939: 6]  | | | | | {"B","1",},
:[.s.:     940: 6]  | | | | | {"A","1",},
:[   :     941: 5]  | | | | <<< }
:[.s.:     942: 5]  | | | | {"IsParagraph","False",},
:[.s.:     943: 5]  | | | | {"AllowScroll","False",},
:[.s.:     944: 5]  | | | | {"ForceUpperCase","False",},
:[.s.:     945: 5]  | | | | {"AutoAdjustHeight","False",},
:[.s.:     946: 5]  | | | | {"FontIndex","1",},
{[PS.:     947: 5]  | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:     948: 6]  | | | | | {"Vertical","Bottom",},
:[.S.:     949: 6]  | | | | | {"Horizontal","Center",},
:[   :     950: 5]  | | | | <<< }
:[   :     951: 4]  | | | <<< }
{[PSU:     952: 4]  | | | "Active", / {"Active","TkNGuiTextStyleData.xml",},
{[PS.:     953: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     954: 6]  | | | | | {"R","1",},
:[.s.:     955: 6]  | | | | | {"G","1",},
:[.s.:     956: 6]  | | | | | {"B","1",},
:[.s.:     957: 6]  | | | | | {"A","1",},
:[   :     958: 5]  | | | | <<< }
:[.s.:     959: 5]  | | | | {"FontHeight","24",},
:[.s.:     960: 5]  | | | | {"FontSpacing","0",},
:[.s.:     961: 5]  | | | | {"IsIndented","False",},
:[.s.:     962: 5]  | | | | {"HasDropShadow","False",},
{[PS.:     963: 5]  | | | | "DropShadowColour", / {"DropShadowColour","Colour.xml",},
:[.s.:     964: 6]  | | | | | {"R","0",},
:[.s.:     965: 6]  | | | | | {"G","0",},
:[.s.:     966: 6]  | | | | | {"B","0",},
:[.s.:     967: 6]  | | | | | {"A","1",},
:[   :     968: 5]  | | | | <<< }
:[.s.:     969: 5]  | | | | {"DropShadowAngle","0",},
:[.s.:     970: 5]  | | | | {"DropShadowOffset","1",},
:[.s.:     971: 5]  | | | | {"HasOutline","False",},
:[.s.:     972: 5]  | | | | {"OutlineSize","1",},
{[PS.:     973: 5]  | | | | "OutlineColour", / {"OutlineColour","Colour.xml",},
:[.s.:     974: 6]  | | | | | {"R","1",},
:[.s.:     975: 6]  | | | | | {"G","1",},
:[.s.:     976: 6]  | | | | | {"B","1",},
:[.s.:     977: 6]  | | | | | {"A","1",},
:[   :     978: 5]  | | | | <<< }
:[.s.:     979: 5]  | | | | {"IsParagraph","False",},
:[.s.:     980: 5]  | | | | {"AllowScroll","False",},
:[.s.:     981: 5]  | | | | {"ForceUpperCase","False",},
:[.s.:     982: 5]  | | | | {"AutoAdjustHeight","False",},
:[.s.:     983: 5]  | | | | {"FontIndex","1",},
{[PS.:     984: 5]  | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:     985: 6]  | | | | | {"Vertical","Bottom",},
:[.S.:     986: 6]  | | | | | {"Horizontal","Center",},
:[   :     987: 5]  | | | | <<< }
:[   :     988: 4]  | | | <<< }
:[   :     989: 3]  | | <<< }
{[PSU:     990: 3]  | | "GraphicStyle", / {"GraphicStyle","TkNGuiGraphicStyle.xml",},
{[PS.:     991: 4]  | | | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:     992: 5]  | | | | {"PaddingX","0",},
:[.s.:     993: 5]  | | | | {"PaddingY","0",},
:[.s.:     994: 5]  | | | | {"MarginX","0",},
:[.s.:     995: 5]  | | | | {"MarginY","0",},
{[PS.:     996: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:     997: 6]  | | | | | {"R","0",},
:[.s.:     998: 6]  | | | | | {"G","0",},
:[.s.:     999: 6]  | | | | | {"B","0",},
:[.s.:    1000: 6]  | | | | | {"A","1",},
:[   :    1001: 5]  | | | | <<< }
{[PS.:    1002: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:    1003: 6]  | | | | | {"R","1",},
:[.s.:    1004: 6]  | | | | | {"G","1",},
:[.s.:    1005: 6]  | | | | | {"B","1",},
:[.s.:    1006: 6]  | | | | | {"A","1",},
:[   :    1007: 5]  | | | | <<< }
{[PS.:    1008: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:    1009: 6]  | | | | | {"R","1",},
:[.s.:    1010: 6]  | | | | | {"G","1",},
:[.s.:    1011: 6]  | | | | | {"B","1",},
:[.s.:    1012: 6]  | | | | | {"A","1",},
:[   :    1013: 5]  | | | | <<< }
:[.S.:    1014: 5]  | | | | {"Shape","Rectangle",},
:[.s.:    1015: 5]  | | | | {"SolidColour","False",},
:[.s.:    1016: 5]  | | | | {"HasDropShadow","False",},
:[.s.:    1017: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:    1018: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:    1019: 5]  | | | | {"Gradient","None",},
:[.s.:    1020: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:    1021: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:    1022: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:    1023: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:    1024: 6]  | | | | | {"R","0",},
:[.s.:    1025: 6]  | | | | | {"G","0",},
:[.s.:    1026: 6]  | | | | | {"B","0",},
:[.s.:    1027: 6]  | | | | | {"A","1",},
:[   :    1028: 5]  | | | | <<< }
:[.s.:    1029: 5]  | | | | {"CornerRadius","0",},
:[.s.:    1030: 5]  | | | | {"StrokeSize","0",},
:[.s.:    1031: 5]  | | | | {"Image","0",},
:[.s.:    1032: 5]  | | | | {"Icon","0",},
:[.s.:    1033: 5]  | | | | {"StrokeGradient","False",},
:[.s.:    1034: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:    1035: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:    1036: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:    1037: 6]  | | | | | {"R","1",},
:[.s.:    1038: 6]  | | | | | {"G","1",},
:[.s.:    1039: 6]  | | | | | {"B","1",},
:[.s.:    1040: 6]  | | | | | {"A","1",},
:[   :    1041: 5]  | | | | <<< }
:[   :    1042: 4]  | | | <<< }
{[PS.:    1043: 4]  | | | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:    1044: 5]  | | | | {"PaddingX","0",},
:[.s.:    1045: 5]  | | | | {"PaddingY","0",},
:[.s.:    1046: 5]  | | | | {"MarginX","0",},
:[.s.:    1047: 5]  | | | | {"MarginY","0",},
{[PS.:    1048: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:    1049: 6]  | | | | | {"R","0",},
:[.s.:    1050: 6]  | | | | | {"G","0",},
:[.s.:    1051: 6]  | | | | | {"B","0",},
:[.s.:    1052: 6]  | | | | | {"A","1",},
:[   :    1053: 5]  | | | | <<< }
{[PS.:    1054: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:    1055: 6]  | | | | | {"R","1",},
:[.s.:    1056: 6]  | | | | | {"G","1",},
:[.s.:    1057: 6]  | | | | | {"B","1",},
:[.s.:    1058: 6]  | | | | | {"A","1",},
:[   :    1059: 5]  | | | | <<< }
{[PS.:    1060: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:    1061: 6]  | | | | | {"R","1",},
:[.s.:    1062: 6]  | | | | | {"G","1",},
:[.s.:    1063: 6]  | | | | | {"B","1",},
:[.s.:    1064: 6]  | | | | | {"A","1",},
:[   :    1065: 5]  | | | | <<< }
:[.S.:    1066: 5]  | | | | {"Shape","Rectangle",},
:[.s.:    1067: 5]  | | | | {"SolidColour","False",},
:[.s.:    1068: 5]  | | | | {"HasDropShadow","False",},
:[.s.:    1069: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:    1070: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:    1071: 5]  | | | | {"Gradient","None",},
:[.s.:    1072: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:    1073: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:    1074: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:    1075: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:    1076: 6]  | | | | | {"R","0",},
:[.s.:    1077: 6]  | | | | | {"G","0",},
:[.s.:    1078: 6]  | | | | | {"B","0",},
:[.s.:    1079: 6]  | | | | | {"A","1",},
:[   :    1080: 5]  | | | | <<< }
:[.s.:    1081: 5]  | | | | {"CornerRadius","0",},
:[.s.:    1082: 5]  | | | | {"StrokeSize","0",},
:[.s.:    1083: 5]  | | | | {"Image","0",},
:[.s.:    1084: 5]  | | | | {"Icon","0",},
:[.s.:    1085: 5]  | | | | {"StrokeGradient","False",},
:[.s.:    1086: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:    1087: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:    1088: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:    1089: 6]  | | | | | {"R","1",},
:[.s.:    1090: 6]  | | | | | {"G","1",},
:[.s.:    1091: 6]  | | | | | {"B","1",},
:[.s.:    1092: 6]  | | | | | {"A","1",},
:[   :    1093: 5]  | | | | <<< }
:[   :    1094: 4]  | | | <<< }
{[PS.:    1095: 4]  | | | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:    1096: 5]  | | | | {"PaddingX","0",},
:[.s.:    1097: 5]  | | | | {"PaddingY","0",},
:[.s.:    1098: 5]  | | | | {"MarginX","0",},
:[.s.:    1099: 5]  | | | | {"MarginY","0",},
{[PS.:    1100: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:    1101: 6]  | | | | | {"R","0",},
:[.s.:    1102: 6]  | | | | | {"G","0",},
:[.s.:    1103: 6]  | | | | | {"B","0",},
:[.s.:    1104: 6]  | | | | | {"A","1",},
:[   :    1105: 5]  | | | | <<< }
{[PS.:    1106: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:    1107: 6]  | | | | | {"R","1",},
:[.s.:    1108: 6]  | | | | | {"G","1",},
:[.s.:    1109: 6]  | | | | | {"B","1",},
:[.s.:    1110: 6]  | | | | | {"A","1",},
:[   :    1111: 5]  | | | | <<< }
{[PS.:    1112: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:    1113: 6]  | | | | | {"R","1",},
:[.s.:    1114: 6]  | | | | | {"G","1",},
:[.s.:    1115: 6]  | | | | | {"B","1",},
:[.s.:    1116: 6]  | | | | | {"A","1",},
:[   :    1117: 5]  | | | | <<< }
:[.S.:    1118: 5]  | | | | {"Shape","Rectangle",},
:[.s.:    1119: 5]  | | | | {"SolidColour","False",},
:[.s.:    1120: 5]  | | | | {"HasDropShadow","False",},
:[.s.:    1121: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:    1122: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:    1123: 5]  | | | | {"Gradient","None",},
:[.s.:    1124: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:    1125: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:    1126: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:    1127: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:    1128: 6]  | | | | | {"R","0",},
:[.s.:    1129: 6]  | | | | | {"G","0",},
:[.s.:    1130: 6]  | | | | | {"B","0",},
:[.s.:    1131: 6]  | | | | | {"A","1",},
:[   :    1132: 5]  | | | | <<< }
:[.s.:    1133: 5]  | | | | {"CornerRadius","0",},
:[.s.:    1134: 5]  | | | | {"StrokeSize","0",},
:[.s.:    1135: 5]  | | | | {"Image","0",},
:[.s.:    1136: 5]  | | | | {"Icon","0",},
:[.s.:    1137: 5]  | | | | {"StrokeGradient","False",},
:[.s.:    1138: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:    1139: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:    1140: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:    1141: 6]  | | | | | {"R","1",},
:[.s.:    1142: 6]  | | | | | {"G","1",},
:[.s.:    1143: 6]  | | | | | {"B","1",},
:[.s.:    1144: 6]  | | | | | {"A","1",},
:[   :    1145: 5]  | | | | <<< }
:[   :    1146: 4]  | | | <<< }
:[.s.:    1147: 4]  | | | {"InheritStyleFromParentLayer","False",},
:[.s.:    1148: 4]  | | | {"HighlightTime","0.1",},
:[.s.:    1149: 4]  | | | {"HighlightScale","1",},
:[.s.:    1150: 4]  | | | {"GlobalFade","1",},
:[.S.:    1151: 4]  | | | {"Animate","None",},
:[.s.:    1152: 4]  | | | {"AnimTime","0.5",},
:[.s.:    1153: 4]  | | | {"AnimSplit","0.4",},
{[PS.:    1154: 4]  | | | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:    1155: 5]  | | | | {"Curve","Linear",},
:[   :    1156: 4]  | | | <<< }
{[PS.:    1157: 4]  | | | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:    1158: 5]  | | | | {"Curve","Linear",},
:[   :    1159: 4]  | | | <<< }
{[PS.:    1160: 4]  | | | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:    1161: 5]  | | | | {"x","1",},
:[.s.:    1162: 5]  | | | | {"y","1",},
:[   :    1163: 4]  | | | <<< }
{[PS.:    1164: 4]  | | | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:    1165: 5]  | | | | {"x","1",},
:[.s.:    1166: 5]  | | | | {"y","1",},
:[   :    1167: 4]  | | | <<< }
:[   :    1168: 3]  | | <<< }
:[.SU:    1170: 3]  | | {"Text","HOLD BUTTON TO SKIP",},
:[.su:    1171: 3]  | | {"Special","True",},
:[   :    1174: 2]  | <<< }
{[P..:    1175: 2]  | "GcNGuiLayerData.xml",
{[PS.:    1176: 3]  | | "ElementData", / {"ElementData","GcNGuiElementData.xml",},
:[.SU:    1177: 4]  | | | {"ID","MSG_HOLD_BAR",},
:[.s.:    1179: 4]  | | | {"IsHidden","True",},
{[PS.:    1180: 4]  | | | "Layout", / {"Layout","GcNGuiLayoutData.xml",},
:[.s.:    1181: 5]  | | | | {"PositionX","50",},
:[.su:    1182: 5]  | | | | {"PositionY","94.5",},
:[.su:    1183: 5]  | | | | {"Width","9.999999",},
:[.s.:    1184: 5]  | | | | {"WidthPercentage","True",},
:[.su:    1185: 5]  | | | | {"Height","2",},
:[.s.:    1186: 5]  | | | | {"HeightPercentage","False",},
:[.s.:    1187: 5]  | | | | {"ConstrainProportions","False",},
:[.s.:    1188: 5]  | | | | {"ConstrainAspect","1",},
:[.s.:    1189: 5]  | | | | {"ForceAspect","False",},
:[.s.:    1190: 5]  | | | | {"Anchor","True",},
:[.s.:    1191: 5]  | | | | {"AnchorPercent","True",},
:[.s.:    1192: 5]  | | | | {"SameLine","False",},
{[PS.:    1193: 5]  | | | | "Align", / {"Align","TkNGuiAlignment.xml",},
:[.S.:    1194: 6]  | | | | | {"Vertical","Bottom",},
:[.S.:    1195: 6]  | | | | | {"Horizontal","Center",},
:[   :    1196: 5]  | | | | <<< }
:[.s.:    1197: 5]  | | | | {"SlowCursorOnHover","False",},
:[.s.:    1198: 5]  | | | | {"MaxWidth","0",},
:[   :    1201: 4]  | | | <<< }
:[   :    1202: 3]  | | <<< }
{[PS.:    1203: 3]  | | "Style", / {"Style","TkNGuiGraphicStyle.xml",},
{[PS.:    1204: 4]  | | | "Default", / {"Default","TkNGuiGraphicStyleData.xml",},
:[.s.:    1205: 5]  | | | | {"PaddingX","0",},
:[.s.:    1206: 5]  | | | | {"PaddingY","0",},
:[.s.:    1207: 5]  | | | | {"MarginX","0",},
:[.s.:    1208: 5]  | | | | {"MarginY","0",},
{[PS.:    1209: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:    1210: 6]  | | | | | {"R","1",},
:[.s.:    1211: 6]  | | | | | {"G","1",},
:[.s.:    1212: 6]  | | | | | {"B","1",},
:[.s.:    1213: 6]  | | | | | {"A","1",},
:[   :    1214: 5]  | | | | <<< }
{[PS.:    1215: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:    1216: 6]  | | | | | {"R","1",},
:[.s.:    1217: 6]  | | | | | {"G","1",},
:[.s.:    1218: 6]  | | | | | {"B","1",},
:[.s.:    1219: 6]  | | | | | {"A","1",},
:[   :    1220: 5]  | | | | <<< }
{[PS.:    1221: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:    1222: 6]  | | | | | {"R","1",},
:[.s.:    1223: 6]  | | | | | {"G","1",},
:[.s.:    1224: 6]  | | | | | {"B","1",},
:[.s.:    1225: 6]  | | | | | {"A","1",},
:[   :    1226: 5]  | | | | <<< }
:[.S.:    1227: 5]  | | | | {"Shape","Rectangle",},
:[.s.:    1228: 5]  | | | | {"SolidColour","True",},
:[.s.:    1229: 5]  | | | | {"HasDropShadow","False",},
:[.s.:    1230: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:    1231: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:    1232: 5]  | | | | {"Gradient","None",},
:[.s.:    1233: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:    1234: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:    1235: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:    1236: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:    1237: 6]  | | | | | {"R","0",},
:[.s.:    1238: 6]  | | | | | {"G","0",},
:[.s.:    1239: 6]  | | | | | {"B","0",},
:[.s.:    1240: 6]  | | | | | {"A","1",},
:[   :    1241: 5]  | | | | <<< }
:[.s.:    1242: 5]  | | | | {"CornerRadius","0",},
:[.s.:    1243: 5]  | | | | {"StrokeSize","0",},
:[.s.:    1244: 5]  | | | | {"Image","0",},
:[.s.:    1245: 5]  | | | | {"Icon","0",},
:[.s.:    1246: 5]  | | | | {"StrokeGradient","False",},
:[.s.:    1247: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:    1248: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:    1249: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:    1250: 6]  | | | | | {"R","1",},
:[.s.:    1251: 6]  | | | | | {"G","1",},
:[.s.:    1252: 6]  | | | | | {"B","1",},
:[.s.:    1253: 6]  | | | | | {"A","1",},
:[   :    1254: 5]  | | | | <<< }
:[   :    1255: 4]  | | | <<< }
{[PS.:    1256: 4]  | | | "Highlight", / {"Highlight","TkNGuiGraphicStyleData.xml",},
:[.s.:    1257: 5]  | | | | {"PaddingX","0",},
:[.s.:    1258: 5]  | | | | {"PaddingY","0",},
:[.s.:    1259: 5]  | | | | {"MarginX","0",},
:[.s.:    1260: 5]  | | | | {"MarginY","0",},
{[PS.:    1261: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:    1262: 6]  | | | | | {"R","1",},
:[.s.:    1263: 6]  | | | | | {"G","1",},
:[.s.:    1264: 6]  | | | | | {"B","1",},
:[.s.:    1265: 6]  | | | | | {"A","1",},
:[   :    1266: 5]  | | | | <<< }
{[PS.:    1267: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:    1268: 6]  | | | | | {"R","1",},
:[.s.:    1269: 6]  | | | | | {"G","1",},
:[.s.:    1270: 6]  | | | | | {"B","1",},
:[.s.:    1271: 6]  | | | | | {"A","1",},
:[   :    1272: 5]  | | | | <<< }
{[PS.:    1273: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:    1274: 6]  | | | | | {"R","1",},
:[.s.:    1275: 6]  | | | | | {"G","1",},
:[.s.:    1276: 6]  | | | | | {"B","1",},
:[.s.:    1277: 6]  | | | | | {"A","1",},
:[   :    1278: 5]  | | | | <<< }
:[.S.:    1279: 5]  | | | | {"Shape","Rectangle",},
:[.s.:    1280: 5]  | | | | {"SolidColour","True",},
:[.s.:    1281: 5]  | | | | {"HasDropShadow","False",},
:[.s.:    1282: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:    1283: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:    1284: 5]  | | | | {"Gradient","None",},
:[.s.:    1285: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:    1286: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:    1287: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:    1288: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:    1289: 6]  | | | | | {"R","0",},
:[.s.:    1290: 6]  | | | | | {"G","0",},
:[.s.:    1291: 6]  | | | | | {"B","0",},
:[.s.:    1292: 6]  | | | | | {"A","1",},
:[   :    1293: 5]  | | | | <<< }
:[.s.:    1294: 5]  | | | | {"CornerRadius","0",},
:[.s.:    1295: 5]  | | | | {"StrokeSize","0",},
:[.s.:    1296: 5]  | | | | {"Image","0",},
:[.s.:    1297: 5]  | | | | {"Icon","0",},
:[.s.:    1298: 5]  | | | | {"StrokeGradient","False",},
:[.s.:    1299: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:    1300: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:    1301: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:    1302: 6]  | | | | | {"R","1",},
:[.s.:    1303: 6]  | | | | | {"G","1",},
:[.s.:    1304: 6]  | | | | | {"B","1",},
:[.s.:    1305: 6]  | | | | | {"A","1",},
:[   :    1306: 5]  | | | | <<< }
:[   :    1307: 4]  | | | <<< }
{[PS.:    1308: 4]  | | | "Active", / {"Active","TkNGuiGraphicStyleData.xml",},
:[.s.:    1309: 5]  | | | | {"PaddingX","0",},
:[.s.:    1310: 5]  | | | | {"PaddingY","0",},
:[.s.:    1311: 5]  | | | | {"MarginX","0",},
:[.s.:    1312: 5]  | | | | {"MarginY","0",},
{[PS.:    1313: 5]  | | | | "Colour", / {"Colour","Colour.xml",},
:[.s.:    1314: 6]  | | | | | {"R","1",},
:[.s.:    1315: 6]  | | | | | {"G","1",},
:[.s.:    1316: 6]  | | | | | {"B","1",},
:[.s.:    1317: 6]  | | | | | {"A","1",},
:[   :    1318: 5]  | | | | <<< }
{[PS.:    1319: 5]  | | | | "IconColour", / {"IconColour","Colour.xml",},
:[.s.:    1320: 6]  | | | | | {"R","1",},
:[.s.:    1321: 6]  | | | | | {"G","1",},
:[.s.:    1322: 6]  | | | | | {"B","1",},
:[.s.:    1323: 6]  | | | | | {"A","1",},
:[   :    1324: 5]  | | | | <<< }
{[PS.:    1325: 5]  | | | | "StrokeColour", / {"StrokeColour","Colour.xml",},
:[.s.:    1326: 6]  | | | | | {"R","1",},
:[.s.:    1327: 6]  | | | | | {"G","1",},
:[.s.:    1328: 6]  | | | | | {"B","1",},
:[.s.:    1329: 6]  | | | | | {"A","1",},
:[   :    1330: 5]  | | | | <<< }
:[.S.:    1331: 5]  | | | | {"Shape","Rectangle",},
:[.s.:    1332: 5]  | | | | {"SolidColour","True",},
:[.s.:    1333: 5]  | | | | {"HasDropShadow","False",},
:[.s.:    1334: 5]  | | | | {"HasOuterGradient","False",},
:[.s.:    1335: 5]  | | | | {"HasInnerGradient","False",},
:[.S.:    1336: 5]  | | | | {"Gradient","None",},
:[.s.:    1337: 5]  | | | | {"GradientStartOffset","0",},
:[.s.:    1338: 5]  | | | | {"GradientEndOffset","0",},
:[.s.:    1339: 5]  | | | | {"GradientOffsetPercent","False",},
{[PS.:    1340: 5]  | | | | "GradientColour", / {"GradientColour","Colour.xml",},
:[.s.:    1341: 6]  | | | | | {"R","0",},
:[.s.:    1342: 6]  | | | | | {"G","0",},
:[.s.:    1343: 6]  | | | | | {"B","0",},
:[.s.:    1344: 6]  | | | | | {"A","1",},
:[   :    1345: 5]  | | | | <<< }
:[.s.:    1346: 5]  | | | | {"CornerRadius","0",},
:[.s.:    1347: 5]  | | | | {"StrokeSize","0",},
:[.s.:    1348: 5]  | | | | {"Image","0",},
:[.s.:    1349: 5]  | | | | {"Icon","0",},
:[.s.:    1350: 5]  | | | | {"StrokeGradient","False",},
:[.s.:    1351: 5]  | | | | {"StrokeGradientOffset","0",},
:[.s.:    1352: 5]  | | | | {"StrokeGradientFeather","0",},
{[PS.:    1353: 5]  | | | | "StrokeGradientColour", / {"StrokeGradientColour","Colour.xml",},
:[.s.:    1354: 6]  | | | | | {"R","1",},
:[.s.:    1355: 6]  | | | | | {"G","1",},
:[.s.:    1356: 6]  | | | | | {"B","1",},
:[.s.:    1357: 6]  | | | | | {"A","1",},
:[   :    1358: 5]  | | | | <<< }
:[   :    1359: 4]  | | | <<< }
:[.s.:    1360: 4]  | | | {"InheritStyleFromParentLayer","False",},
:[.s.:    1361: 4]  | | | {"HighlightTime","0.1",},
:[.s.:    1362: 4]  | | | {"HighlightScale","1",},
:[.s.:    1363: 4]  | | | {"GlobalFade","1",},
:[.S.:    1364: 4]  | | | {"Animate","None",},
:[.s.:    1365: 4]  | | | {"AnimTime","0.5",},
:[.s.:    1366: 4]  | | | {"AnimSplit","0.4",},
{[PS.:    1367: 4]  | | | "AnimCurve1", / {"AnimCurve1","TkCurveType.xml",},
:[.S.:    1368: 5]  | | | | {"Curve","Linear",},
:[   :    1369: 4]  | | | <<< }
{[PS.:    1370: 4]  | | | "AnimCurve2", / {"AnimCurve2","TkCurveType.xml",},
:[.S.:    1371: 5]  | | | | {"Curve","Linear",},
:[   :    1372: 4]  | | | <<< }
{[PS.:    1373: 4]  | | | "CustomMinStart", / {"CustomMinStart","Vector2f.xml",},
:[.s.:    1374: 5]  | | | | {"x","1",},
:[.s.:    1375: 5]  | | | | {"y","1",},
:[   :    1376: 4]  | | | <<< }
{[PS.:    1377: 4]  | | | "CustomMaxStart", / {"CustomMaxStart","Vector2f.xml",},
:[.s.:    1378: 5]  | | | | {"x","1",},
:[.s.:    1379: 5]  | | | | {"y","1",},
:[   :    1380: 4]  | | | <<< }
:[   :    1381: 3]  | | <<< }
:[.S.:    1385: 3]  | | {"AltMode","None",},
:[   :    1386: 2]  | <<< }
:[   :    1387: 1]  <<< }
:[.SU:    1388: 1]  {"DataFilename","UI/HUD/HUDBARS.MBIN",},
:[.S.:    1389: 1]  {"AltMode","None",},
:[   :    1390: 0]/Data } --Do not use, NOT a KEYWORD
 TYPE:FILELINE:LEVEL     KEYWORDS
 TYPE = 'P'receding, 'S/s'pecial, 'U/u'nique
 [WARNING] Lower case 's/u' are Special/Unique with 'True', 'False' or a number
>>> MapFileTree: UI\HUD\HUDBARS.EXML (NMSARC.515F1D3.pak) "2022/03/16-18:34:38"
